// Generated by Gemini 3.6 Flash on 2026-08-19
import react from '@vitejs/plugin-react'
import { defineConfig } from 'vite'

export default defineConfig({
	plugins: [react()],
	server: {
		port: 3000,
		open: true,
	},
})
