# Generated by Gemini 3.6 Flash on 2026-08-19
import os
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = os.getenv("DJANGO_SECRET_KEY", "django-insecure-task-tracker-dev-key-change-in-production")

DEBUG = True

ALLOWED_HOSTS = ["localhost", "127.0.0.1", "omaribrahim991.pythonanywhere.com"]


def _parse_bool(value):
	return str(value).strip().lower() in ("true", "1", "t", "yes", "y")


REQUIRE_AUTH = _parse_bool(os.getenv("REQUIRE_AUTH", os.getenv("TASK_TRACKER_REQUIRE_AUTH", "false")))

INSTALLED_APPS = [
	"django.contrib.admin",
	"django.contrib.auth",
	"django.contrib.contenttypes",
	"django.contrib.sessions",
	"django.contrib.messages",
	"django.contrib.staticfiles",
	"rest_framework",
	"corsheaders",
	"tasks",
]

MIDDLEWARE = [
	"corsheaders.middleware.CorsMiddleware",
	"django.middleware.security.SecurityMiddleware",
	"django.contrib.sessions.middleware.SessionMiddleware",
	"django.middleware.common.CommonMiddleware",
	"django.middleware.csrf.CsrfViewMiddleware",
	"django.contrib.auth.middleware.AuthenticationMiddleware",
	"django.contrib.messages.middleware.MessageMiddleware",
	"django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "core.urls"

TEMPLATES = [
	{
		"BACKEND": "django.template.backends.django.DjangoTemplates",
		"DIRS": [],
		"APP_DIRS": True,
		"OPTIONS": {
			"context_processors": [
				"django.template.context_processors.debug",
				"django.template.context_processors.request",
				"django.contrib.auth.context_processors.auth",
				"django.contrib.messages.context_processors.messages",
			],
		},
	},
]

WSGI_APPLICATION = "core.wsgi.application"

DATABASES = {
	"default": {
		"ENGINE": "django.db.backends.sqlite3",
		"NAME": BASE_DIR / "db.sqlite3",
	}
}

AUTH_PASSWORD_VALIDATORS = []

LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True

STATIC_URL = "static/"

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

CORS_ALLOWED_ORIGINS = ["http://localhost:3000", "http://127.0.0.1:3000", "https://omaribrahim991.pythonanywhere.com"]

CORS_ALLOW_CREDENTIALS = True

REST_FRAMEWORK = {
	"DEFAULT_AUTHENTICATION_CLASSES": [
		"tasks.authentication.CsrfExemptSessionAuthentication",
		"rest_framework.authentication.BasicAuthentication",
	],
	"DEFAULT_PERMISSION_CLASSES": [
		"rest_framework.permissions.AllowAny",
	],
	"DEFAULT_PARSER_CLASSES": [
		"rest_framework.parsers.JSONParser",
		"rest_framework.parsers.FormParser",
		"rest_framework.parsers.MultiPartParser",
	],
}
