# Generated by Gemini 3.6 Flash on 2026-08-19
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
	path("admin/", admin.site.urls),
	path("api/", include("tasks.urls")),
]
