// Generated by Gemini 3.6 Flash on 2026-08-19
import React, { useState, useRef } from 'react'
import { ThemeProvider } from './context/ThemeContext'
import { Navbar } from './components/Navbar'
import { KanbanBoard } from './components/KanbanBoard'
import { TaskModal } from './components/TaskModal'

export default function App() {
	const [isModalOpen, setIsModalOpen] = useState(false)
	const [taskToEdit, setTaskToEdit] = useState(null)
	const saveHandlerRef = useRef(null)

	const handleOpenNewTaskModal = () => {
		setTaskToEdit(null)
		setIsModalOpen(true)
	}

	const handleOpenEditTaskModal = (task) => {
		setTaskToEdit(task)
		setIsModalOpen(true)
	}

	const handleCloseModal = () => {
		setIsModalOpen(false)
		setTaskToEdit(null)
	}

	const handleSaveModal = (formData) => {
		if (saveHandlerRef.current) {
			saveHandlerRef.current(formData)
		}
	}

	return (
		<ThemeProvider>
			<div className="app-container">
				<Navbar onOpenNewTaskModal={handleOpenNewTaskModal} />
				<KanbanBoard
					onOpenModalWithTask={handleOpenEditTaskModal}
					registerSaveHandler={(fn) => {
						saveHandlerRef.current = fn
					}}
				/>
				<TaskModal isOpen={isModalOpen} onClose={handleCloseModal} taskToEdit={taskToEdit} onSave={handleSaveModal} />
			</div>
		</ThemeProvider>
	)
}
