// Generated by Gemini 3.6 Flash on 2026-08-19
import { useCallback, useEffect, useRef, useState } from "react"
import { Route, Switch } from "wouter"
import { KanbanBoard } from "./components/KanbanBoard"
import { Navbar } from "./components/Navbar"
import { TaskModal } from "./components/TaskModal"
import { ThemeProvider } from "./context/ThemeContext"
import { ProjectsPage } from "./pages/ProjectsPage"
import { projectApi } from "./services/api"

export default function App() {
	const [isModalOpen, setIsModalOpen] = useState(false)
	const [taskToEdit, setTaskToEdit] = useState(null)
	const saveHandlerRef = useRef(null)

	const [projects, setProjects] = useState([])
	const [enabledProjectIds, setEnabledProjectIds] = useState([])
	const [projectsLoading, setProjectsLoading] = useState(true)

	const fetchProjects = useCallback(async () => {
		try {
			setProjectsLoading(true)
			setProjects(await projectApi.getProjects())
		} catch {
			// Projects will remain empty on failure
		} finally {
			setProjectsLoading(false)
		}
	}, [])

	useEffect(() => {
		fetchProjects()
	}, [fetchProjects])

	const handleToggleProject = (projectId) => {
		setEnabledProjectIds((current) => (current.includes(projectId) ? current.filter((id) => id !== projectId) : [...current, projectId]))
	}

	const handleOpenNewTaskModal = () => {
		setTaskToEdit(null)
		setIsModalOpen(true)
	}

	const handleOpenEditTaskModal = (task) => {
		setTaskToEdit(task)
		setIsModalOpen(true)
	}

	const handleCloseModal = () => {
		setIsModalOpen(false)
		setTaskToEdit(null)
	}

	const handleSaveModal = (formData) => {
		if (saveHandlerRef.current) {
			saveHandlerRef.current(formData)
		}
	}

	return (
		<ThemeProvider>
			<div className="app-container">
				<Navbar
					onOpenNewTaskModal={handleOpenNewTaskModal}
					projects={projects}
					enabledProjectIds={enabledProjectIds}
					onToggleProject={handleToggleProject}
				/>
				<Switch>
					<Route path="/">
						<KanbanBoard
							onOpenModalWithTask={handleOpenEditTaskModal}
							projects={projects}
							enabledProjectIds={enabledProjectIds}
							projectsLoading={projectsLoading}
							registerSaveHandler={(fn) => {
								saveHandlerRef.current = fn
							}}
						/>
					</Route>
					<Route path="/projects">
						<ProjectsPage onProjectsRefresh={fetchProjects} />
					</Route>
				</Switch>
				<TaskModal isOpen={isModalOpen} onClose={handleCloseModal} taskToEdit={taskToEdit} onSave={handleSaveModal} />
			</div>
		</ThemeProvider>
	)
}
