# Generated by Gemini 3.6 Flash on 2026-08-19
from django.contrib import admin
from .models import Task

@admin.register(Task)
class TaskAdmin(admin.ModelAdmin):
    list_display = ('id', 'title', 'status', 'priority', 'assignee', 'created_at')
    list_filter = ('status', 'priority', 'assignee')
    search_fields = ('title', 'description', 'assignee')
