# Generated by Muse Spark on 2026-09-15
from rest_framework.authentication import BasicAuthentication, SessionAuthentication
from rest_framework.exceptions import AuthenticationFailed


class CsrfExemptSessionAuthentication(SessionAuthentication):
	"""Session auth without CSRF enforcement for API use.

	The React client authenticates with real Basic credentials (and the API
	base URL is runtime-configurable, so session cookies are not a reliable
	auth mechanism anyway). Requiring a CSRF token would reject legitimate
	session-authenticated writes from the client, so the API relies on
	IsAuthenticatedIfAuthRequired for protection instead.
	"""

	def enforce_csrf(self, request):
		return


class LenientSessionAuthentication(CsrfExemptSessionAuthentication):
	"""Session auth that treats failures as anonymous instead of raising.

	Used only on public registration views so stale sessions or missing CSRF
	tokens can never block sign-up. Protected endpoints still reject anonymous
	users via IsAuthenticatedIfAuthRequired when REQUIRE_AUTH is True.
	"""

	def authenticate(self, request):
		try:
			return super().authenticate(request)
		except AuthenticationFailed:
			return None


class LenientBasicAuthentication(BasicAuthentication):
	"""Basic auth that treats invalid credentials as anonymous instead of raising."""

	def authenticate(self, request):
		try:
			return super().authenticate(request)
		except AuthenticationFailed:
			return None
