# Generated by Gemini 3.6 Flash on 2026-08-19
from typing import ClassVar

from django.db import models
from django.contrib.auth.models import User


class Project(models.Model):
	name = models.CharField(max_length=255, unique=True)
	created_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now=True)

	class Meta:
		ordering: ClassVar[list[str]] = ["-created_at"]

	def __str__(self):
		return self.name


class Task(models.Model):
	STATUS_CHOICES: ClassVar[list[tuple[str, str]]] = [
		("TODO", "To Do"),
		("IN_PROGRESS", "In Progress"),
		("REVIEW", "Review"),
		("DONE", "Done"),
	]

	PRIORITY_CHOICES: ClassVar[list[tuple[str, str]]] = [
		("LOW", "Low"),
		("MEDIUM", "Medium"),
		("HIGH", "High"),
	]

	title = models.CharField(max_length=255)
	description = models.TextField(blank=True, default="")
	status = models.CharField(max_length=20, choices=STATUS_CHOICES, default="TODO")
	priority = models.CharField(max_length=10, choices=PRIORITY_CHOICES, default="MEDIUM")
	assignee = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name="tasks")
	projects = models.ManyToManyField(Project, blank=True, related_name="tasks")
	position = models.IntegerField(default=0)
	created_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now=True)

	class Meta:
		ordering: ClassVar[list[str]] = ["status", "position", "id"]

	def __str__(self):
		return f"{self.title} ({self.get_status_display()})"
