# Generated by Gemini 3.1 Pro on 2026-09-15
from django.conf import settings
from rest_framework.permissions import BasePermission


class IsAuthenticatedIfAuthRequired(BasePermission):
	"""
	Allows access only to authenticated users if settings.REQUIRE_AUTH is True.
	Otherwise, allows access to anyone.
	"""

	def has_permission(self, request, view):
		if getattr(settings, "REQUIRE_AUTH", False):
			return bool(request.user and request.user.is_authenticated)
		return True
