# Generated by Gemini 3.6 Flash on 2026-08-19
from typing import ClassVar

from rest_framework import serializers

from .models import Task


class TaskSerializer(serializers.ModelSerializer):
	class Meta:
		model = Task
		fields: ClassVar[list[str]] = [
			"id",
			"title",
			"description",
			"status",
			"priority",
			"assignee",
			"created_at",
			"updated_at",
		]
		read_only_fields: ClassVar[list[str]] = ["id", "created_at", "updated_at"]

	def validate_assignee(self, value):
		if not value or not value.strip():
			return "Admin"
		return value
