# Generated by Claude Opus 4.6 on 2026-09-04
from django.contrib.auth.models import User
from django.core.management import call_command
from rest_framework import status
from rest_framework.test import APITestCase

from .models import Project, Task


class ProjectAndTaskAPITests(APITestCase):
	project_url = "/api/projects/"
	task_url = "/api/tasks/"

	def test_project_crud_and_unique_name(self):
		create_response = self.client.post(self.project_url, {"name": "Website refresh"}, format="json")

		self.assertEqual(create_response.status_code, status.HTTP_201_CREATED)
		project_id = create_response.data["id"]
		self.assertEqual(self.client.get(self.project_url).data[0]["name"], "Website refresh")
		self.assertEqual(self.client.get(f"{self.project_url}{project_id}/").status_code, status.HTTP_200_OK)
		self.assertEqual(self.client.post(self.project_url, {"name": "Website refresh"}, format="json").status_code, status.HTTP_400_BAD_REQUEST)
		self.assertEqual(self.client.post(self.project_url, {}, format="json").status_code, status.HTTP_400_BAD_REQUEST)
		self.assertEqual(self.client.delete(f"{self.project_url}{project_id}/").status_code, status.HTTP_204_NO_CONTENT)

	def test_tasks_support_multiple_projects_and_patch_clearing(self):
		projects = [Project.objects.create(name=name) for name in ("Website", "Launch")]
		create_response = self.client.post(self.task_url, {"title": "Review copy", "project_ids": [project.id for project in projects]}, format="json")

		self.assertEqual(create_response.status_code, status.HTTP_201_CREATED)
		self.assertEqual(set(create_response.data["project_ids"]), {project.id for project in projects})
		self.assertEqual({project["name"] for project in create_response.data["projects"]}, {"Website", "Launch"})

		task_id = create_response.data["id"]
		omitted_response = self.client.patch(f"{self.task_url}{task_id}/", {"title": "Review final copy"}, format="json")
		self.assertEqual(set(omitted_response.data["project_ids"]), {project.id for project in projects})

		cleared_response = self.client.patch(f"{self.task_url}{task_id}/", {"project_ids": []}, format="json")
		self.assertEqual(cleared_response.data["project_ids"], [])
		self.assertEqual(cleared_response.data["projects"], [])

	def test_invalid_project_ids_are_rejected(self):
		response = self.client.post(self.task_url, {"title": "Invalid assignment", "project_ids": [999]}, format="json")

		self.assertEqual(response.status_code, status.HTTP_400_BAD_REQUEST)

	def test_unassigned_tasks_are_returned(self):
		response = self.client.post(self.task_url, {"title": "Unassigned"}, format="json")

		self.assertEqual(response.status_code, status.HTTP_201_CREATED)
		self.assertEqual(response.data["project_ids"], [])
		self.assertEqual(response.data["projects"], [])
		self.assertEqual(self.client.get(self.task_url).data[0]["title"], "Unassigned")

	def test_deleting_task_removes_project_associations(self):
		project = Project.objects.create(name="Cleanup")
		task = Task.objects.create(title="Delete me")
		task.projects.add(project)

		self.assertEqual(self.client.delete(f"{self.task_url}{task.id}/").status_code, status.HTTP_204_NO_CONTENT)
		self.assertFalse(project.tasks.filter(id=task.id).exists())

	def test_deleting_project_preserves_tasks_and_removes_association(self):
		project = Project.objects.create(name="Preserve")
		task = Task.objects.create(title="Keep me")
		task.projects.add(project)

		self.assertEqual(self.client.delete(f"{self.project_url}{project.id}/").status_code, status.HTTP_204_NO_CONTENT)
		self.assertTrue(Task.objects.filter(id=task.id).exists())
		self.assertEqual(self.client.get(f"{self.task_url}{task.id}/").data["project_ids"], [])


class UserAPITests(APITestCase):
	user_url = "/api/users/"

	def test_create_user_hashes_password_and_omits_password_in_response(self):
		response = self.client.post(self.user_url, {"username": "testdeveloper", "password": "SecurePassword123!"}, format="json")

		self.assertEqual(response.status_code, status.HTTP_201_CREATED)
		self.assertNotIn("password", response.data)
		user = User.objects.get(username="testdeveloper")
		self.assertTrue(user.check_password("SecurePassword123!"))

	def test_create_user_duplicate_username_fails(self):
		self.client.post(self.user_url, {"username": "duplicate_user", "password": "Pass1234!"}, format="json")
		response = self.client.post(self.user_url, {"username": "duplicate_user", "password": "OtherPass!"}, format="json")

		self.assertEqual(response.status_code, status.HTTP_400_BAD_REQUEST)

	def test_list_users_omits_password_field(self):
		User.objects.create_user(username="visible_user", password="SomePass!")
		response = self.client.get(self.user_url)

		self.assertEqual(response.status_code, status.HTTP_200_OK)
		for user_data in response.data:
			self.assertIn("id", user_data)
			self.assertIn("username", user_data)
			self.assertNotIn("password", user_data)

	def test_user_methods_restricted(self):
		user = User.objects.create_user(username="restricted_user", password="Pass!")
		detail_url = f"{self.user_url}{user.id}/"

		self.assertEqual(self.client.put(detail_url, {"username": "new"}, format="json").status_code, status.HTTP_405_METHOD_NOT_ALLOWED)
		self.assertEqual(self.client.patch(detail_url, {"username": "new"}, format="json").status_code, status.HTTP_405_METHOD_NOT_ALLOWED)
		self.assertEqual(self.client.delete(detail_url).status_code, status.HTTP_405_METHOD_NOT_ALLOWED)


class TaskAPITests(APITestCase):
	task_url = "/api/tasks/"

	def test_create_task_defaults_to_admin_assignee(self):
		response = self.client.post(self.task_url, {"title": "Auto-assigned task", "assignee": None}, format="json")

		self.assertEqual(response.status_code, status.HTTP_201_CREATED)
		self.assertEqual(response.data["assignee_details"]["username"], "Admin")
		self.assertTrue(User.objects.filter(username="Admin").exists())

	def test_create_task_with_custom_assignee(self):
		user = User.objects.create_user(username="maya", password="MayaPass!")
		response = self.client.post(self.task_url, {"title": "Custom assignee task", "assignee": user.id}, format="json")

		self.assertEqual(response.status_code, status.HTTP_201_CREATED)
		self.assertEqual(response.data["assignee_details"]["username"], "maya")

	def test_create_task_validation_missing_title(self):
		response_no_title = self.client.post(self.task_url, {}, format="json")
		self.assertEqual(response_no_title.status_code, status.HTTP_400_BAD_REQUEST)

		response_empty_title = self.client.post(self.task_url, {"title": ""}, format="json")
		self.assertEqual(response_empty_title.status_code, status.HTTP_400_BAD_REQUEST)

	def test_create_task_status_choices_validation(self):
		valid_response = self.client.post(self.task_url, {"title": "Valid status", "status": "REVIEW"}, format="json")
		self.assertEqual(valid_response.status_code, status.HTTP_201_CREATED)

		invalid_response = self.client.post(self.task_url, {"title": "Invalid status", "status": "ARCHIVED"}, format="json")
		self.assertEqual(invalid_response.status_code, status.HTTP_400_BAD_REQUEST)

	def test_create_task_priority_choices_validation(self):
		valid_response = self.client.post(self.task_url, {"title": "Valid priority", "priority": "HIGH"}, format="json")
		self.assertEqual(valid_response.status_code, status.HTTP_201_CREATED)

		invalid_response = self.client.post(self.task_url, {"title": "Invalid priority", "priority": "CRITICAL"}, format="json")
		self.assertEqual(invalid_response.status_code, status.HTTP_400_BAD_REQUEST)

	def test_task_retrieve_update_delete(self):
		create_response = self.client.post(self.task_url, {"title": "Lifecycle task", "description": "Full lifecycle"}, format="json")
		task_id = create_response.data["id"]

		# Retrieve
		retrieve_response = self.client.get(f"{self.task_url}{task_id}/")
		self.assertEqual(retrieve_response.status_code, status.HTTP_200_OK)
		expected_fields = {
			"id",
			"title",
			"description",
			"status",
			"priority",
			"assignee",
			"assignee_details",
			"project_ids",
			"projects",
			"position",
			"created_at",
			"updated_at",
		}
		self.assertTrue(expected_fields.issubset(set(retrieve_response.data.keys())))

		# Update
		update_response = self.client.patch(f"{self.task_url}{task_id}/", {"status": "IN_PROGRESS", "priority": "HIGH"}, format="json")
		self.assertEqual(update_response.status_code, status.HTTP_200_OK)
		self.assertEqual(update_response.data["status"], "IN_PROGRESS")
		self.assertEqual(update_response.data["priority"], "HIGH")

		# Delete
		delete_response = self.client.delete(f"{self.task_url}{task_id}/")
		self.assertEqual(delete_response.status_code, status.HTTP_204_NO_CONTENT)
		self.assertFalse(Task.objects.filter(id=task_id).exists())


class TaskReorderAPITests(APITestCase):
	task_url = "/api/tasks/"

	def setUp(self):
		self.t0 = Task.objects.create(title="T0", status="TODO", position=0)
		self.t1 = Task.objects.create(title="T1", status="TODO", position=1)
		self.t2 = Task.objects.create(title="T2", status="TODO", position=2)

	def test_reorder_task_within_same_column(self):
		response = self.client.post(f"{self.task_url}{self.t2.id}/reorder/", {"status": "TODO", "target_task_id": self.t1.id}, format="json")

		self.assertEqual(response.status_code, status.HTTP_200_OK)
		positions = list(Task.objects.filter(status="TODO").order_by("position").values_list("id", "position"))
		ids_in_order = [p[0] for p in positions]
		self.assertIn(self.t2.id, ids_in_order)
		# Positions should be sequential 0, 1, 2
		self.assertEqual([p[1] for p in positions], [0, 1, 2])

	def test_reorder_task_to_different_status_column(self):
		ip_task = Task.objects.create(title="IP0", status="IN_PROGRESS", position=0)
		response = self.client.post(f"{self.task_url}{self.t0.id}/reorder/", {"status": "IN_PROGRESS", "target_task_id": ip_task.id}, format="json")

		self.assertEqual(response.status_code, status.HTTP_200_OK)
		self.t0.refresh_from_db()
		self.assertEqual(self.t0.status, "IN_PROGRESS")
		ip_positions = list(Task.objects.filter(status="IN_PROGRESS").order_by("position").values_list("position", flat=True))
		self.assertEqual(ip_positions, list(range(len(ip_positions))))

	def test_reorder_task_to_end_of_column_without_target(self):
		response = self.client.post(f"{self.task_url}{self.t0.id}/reorder/", {"status": "DONE"}, format="json")

		self.assertEqual(response.status_code, status.HTTP_200_OK)
		self.t0.refresh_from_db()
		self.assertEqual(self.t0.status, "DONE")
		done_positions = list(Task.objects.filter(status="DONE").order_by("position").values_list("position", flat=True))
		self.assertEqual(done_positions, list(range(len(done_positions))))

	def test_reorder_invalid_target_task_returns_400(self):
		response = self.client.post(f"{self.task_url}{self.t0.id}/reorder/", {"status": "TODO", "target_task_id": 99999}, format="json")

		self.assertEqual(response.status_code, status.HTTP_400_BAD_REQUEST)
		self.assertIn("detail", response.data)


class SeedTasksCommandTests(APITestCase):
	def test_seed_tasks_command_execution_and_idempotency(self):
		call_command("seed_tasks")

		self.assertTrue(User.objects.filter(username="Admin").exists())
		self.assertTrue(Task.objects.exists())
		initial_count = Task.objects.count()

		# Second call should be idempotent
		call_command("seed_tasks")
		self.assertEqual(Task.objects.count(), initial_count)
