# Generated by GitHub Copilot on 2026-08-25
from rest_framework import status
from rest_framework.test import APITestCase

from .models import Project, Task


class ProjectAndTaskAPITests(APITestCase):
	project_url = "/api/projects/"
	task_url = "/api/tasks/"

	def test_project_crud_and_unique_name(self):
		create_response = self.client.post(self.project_url, {"name": "Website refresh"}, format="json")

		self.assertEqual(create_response.status_code, status.HTTP_201_CREATED)
		project_id = create_response.data["id"]
		self.assertEqual(self.client.get(self.project_url).data[0]["name"], "Website refresh")
		self.assertEqual(self.client.get(f"{self.project_url}{project_id}/").status_code, status.HTTP_200_OK)
		self.assertEqual(self.client.post(self.project_url, {"name": "Website refresh"}, format="json").status_code, status.HTTP_400_BAD_REQUEST)
		self.assertEqual(self.client.post(self.project_url, {}, format="json").status_code, status.HTTP_400_BAD_REQUEST)
		self.assertEqual(self.client.delete(f"{self.project_url}{project_id}/").status_code, status.HTTP_204_NO_CONTENT)

	def test_tasks_support_multiple_projects_and_patch_clearing(self):
		projects = [Project.objects.create(name=name) for name in ("Website", "Launch")]
		create_response = self.client.post(self.task_url, {"title": "Review copy", "project_ids": [project.id for project in projects]}, format="json")

		self.assertEqual(create_response.status_code, status.HTTP_201_CREATED)
		self.assertEqual(set(create_response.data["project_ids"]), {project.id for project in projects})
		self.assertEqual({project["name"] for project in create_response.data["projects"]}, {"Website", "Launch"})

		task_id = create_response.data["id"]
		omitted_response = self.client.patch(f"{self.task_url}{task_id}/", {"title": "Review final copy"}, format="json")
		self.assertEqual(set(omitted_response.data["project_ids"]), {project.id for project in projects})

		cleared_response = self.client.patch(f"{self.task_url}{task_id}/", {"project_ids": []}, format="json")
		self.assertEqual(cleared_response.data["project_ids"], [])
		self.assertEqual(cleared_response.data["projects"], [])

	def test_invalid_project_ids_are_rejected(self):
		response = self.client.post(self.task_url, {"title": "Invalid assignment", "project_ids": [999]}, format="json")

		self.assertEqual(response.status_code, status.HTTP_400_BAD_REQUEST)

	def test_unassigned_tasks_are_returned(self):
		response = self.client.post(self.task_url, {"title": "Unassigned"}, format="json")

		self.assertEqual(response.status_code, status.HTTP_201_CREATED)
		self.assertEqual(response.data["project_ids"], [])
		self.assertEqual(response.data["projects"], [])
		self.assertEqual(self.client.get(self.task_url).data[0]["title"], "Unassigned")

	def test_deleting_task_removes_project_associations(self):
		project = Project.objects.create(name="Cleanup")
		task = Task.objects.create(title="Delete me")
		task.projects.add(project)

		self.assertEqual(self.client.delete(f"{self.task_url}{task.id}/").status_code, status.HTTP_204_NO_CONTENT)
		self.assertFalse(project.tasks.filter(id=task.id).exists())

	def test_deleting_project_preserves_tasks_and_removes_association(self):
		project = Project.objects.create(name="Preserve")
		task = Task.objects.create(title="Keep me")
		task.projects.add(project)

		self.assertEqual(self.client.delete(f"{self.project_url}{project.id}/").status_code, status.HTTP_204_NO_CONTENT)
		self.assertTrue(Task.objects.filter(id=task.id).exists())
		self.assertEqual(self.client.get(f"{self.task_url}{task.id}/").data["project_ids"], [])
