# Generated by Gemini 3.6 Flash on 2026-08-19
from typing import ClassVar

from django.contrib.auth.models import User
from django.db.models import F
from rest_framework import status, viewsets
from rest_framework.decorators import action
from rest_framework.response import Response

from .models import Project, Task
from .serializers import ProjectSerializer, TaskSerializer, UserCreateSerializer, UserSerializer


class UserViewSet(viewsets.ModelViewSet):
	queryset = User.objects.all()
	http_method_names: ClassVar[list[str]] = ["get", "post"]

	def get_serializer_class(self):
		if self.action == "create":
			return UserCreateSerializer
		return UserSerializer


class ProjectViewSet(viewsets.ModelViewSet):
	queryset = Project.objects.all()
	serializer_class = ProjectSerializer


class TaskViewSet(viewsets.ModelViewSet):
	queryset = Task.objects.all()
	serializer_class = TaskSerializer

	def create(self, request, *args, **kwargs):
		serializer = self.get_serializer(data=request.data)
		serializer.is_valid(raise_exception=True)
		self.perform_create(serializer)
		headers = self.get_success_headers(serializer.data)
		return Response(serializer.data, status=status.HTTP_201_CREATED, headers=headers)

	@action(detail=True, methods=["post"])
	def reorder(self, request, pk=None):
		task = self.get_object()
		status_val = request.data.get("status", task.status)
		target_task_id = request.data.get("target_task_id")

		# Calculate new position
		if target_task_id:
			try:
				target_task = Task.objects.get(pk=target_task_id, status=status_val)
				new_position = target_task.position
			except Task.DoesNotExist:
				return Response({"detail": "target_task_id is invalid or not in the target status."}, status=status.HTTP_400_BAD_REQUEST)
		else:
			new_position = 999999  # Placed at the end, will be normalized

		# Reorder existing tasks
		# Shift tasks down to make room
		Task.objects.filter(status=status_val, position__gte=new_position).exclude(pk=task.pk).update(position=F("position") + 1)

		# Update the target task
		task.status = status_val
		task.position = new_position
		task.save()

		# Normalize positions in the target column to prevent gaps/duplicates over time
		target_tasks = Task.objects.filter(status=status_val).order_by("position", "id")
		for idx, t in enumerate(target_tasks):
			if t.position != idx:
				t.position = idx
				t.save()

		return Response(self.get_serializer(task).data)
