// Generated by Muse Spark 1.2 on 2026-08-31
import { useCallback, useEffect, useState } from "react"

export const useApi = (fetcher, { immediate = true, initialData = null } = {}) => {
	const [data, setData] = useState(initialData)
	const [loading, setLoading] = useState(immediate)
	const [error, setError] = useState("")

	const execute = useCallback(
		async (...args) => {
			setLoading(true)
			setError("")
			try {
				const result = await fetcher(...args)
				setData(result)
				return result
			} catch (err) {
				const message = err?.message || "Request failed"
				setError(message)
				throw err
			} finally {
				setLoading(false)
			}
		},
		[fetcher],
	)

	useEffect(() => {
		let ignore = false
		if (immediate) {
			execute().catch(() => {
				if (ignore) return
			})
		}
		return () => {
			ignore = true
		}
	}, [execute, immediate])

	return { data, loading, error, execute, refetch: execute, setData }
}
