// Generated by Muse Spark 1.2 on 2026-08-31
import { useEffect } from "react"

export const useClickOutside = (ref, handler, enabled = true) => {
	useEffect(() => {
		if (!enabled) return

		const fn = (event) => {
			if (ref.current && !ref.current.contains(event.target)) {
				handler(event)
			}
		}

		document.addEventListener("mousedown", fn)
		document.addEventListener("touchstart", fn)
		return () => {
			document.removeEventListener("mousedown", fn)
			document.removeEventListener("touchstart", fn)
		}
	}, [ref, handler, enabled])
}
