// Generated by Muse Spark 1.2 on 2026-08-31
import { useCallback, useEffect, useState } from "react"
import { API_BASE_URL, apiRequest } from "../utils/apiClient"
import { STORAGE_KEY, getQueue, isNetworkError, setQueue } from "../utils/offlineQueue"

const replayMutation = async (item) => {
	const path = item.url.startsWith(API_BASE_URL) ? item.url.slice(API_BASE_URL.length) : item.url
	const method = item.method
	const body = item.body

	if (method === "DELETE") {
		await apiRequest(path, { method })
		return
	}
	await apiRequest(path, { method, body })
}

export const useOfflineQueue = () => {
	const [queue, setQueueState] = useState(() => getQueue())
	const [isOnline, setIsOnline] = useState(() => (typeof navigator !== "undefined" ? navigator.onLine : true))
	const [isSyncing, setIsSyncing] = useState(false)

	const refreshQueue = useCallback(() => {
		setQueueState(getQueue())
	}, [])

	useEffect(() => {
		refreshQueue()
		const handleStorage = (event) => {
			if (event.key === STORAGE_KEY) refreshQueue()
		}
		const handleOnline = () => {
			setIsOnline(true)
		}
		const handleOffline = () => setIsOnline(false)

		window.addEventListener("online", handleOnline)
		window.addEventListener("offline", handleOffline)
		window.addEventListener("storage", handleStorage)
		return () => {
			window.removeEventListener("online", handleOnline)
			window.removeEventListener("offline", handleOffline)
			window.removeEventListener("storage", handleStorage)
		}
	}, [refreshQueue])

	const enqueueMutation = useCallback((mutation) => {
		const current = getQueue()
		const entry = {
			id: `m_${Date.now()}_${Math.random().toString(36).slice(2, 6)}`,
			createdAt: Date.now(),
			attempts: 0,
			...mutation,
		}
		const next = [...current, entry]
		setQueue(next)
		setQueueState(next)
		return entry
	}, [])

	const syncQueue = useCallback(async () => {
		if (isSyncing) return
		let current = getQueue()
		if (current.length === 0 || !navigator.onLine) return

		setIsSyncing(true)
		try {
			while (current.length > 0) {
				const head = current[0]
				try {
					await replayMutation(head)
					current = current.slice(1)
					setQueue(current)
					setQueueState([...current])
				} catch (err) {
					if (isNetworkError(err)) {
						const updated = current.map((item, idx) => (idx === 0 ? { ...item, attempts: (item.attempts || 0) + 1 } : item))
						setQueue(updated)
						setQueueState([...updated])
					}
					break
				}
			}
		} finally {
			setIsSyncing(false)
		}
	}, [isSyncing])

	useEffect(() => {
		if (isOnline && queue.length > 0 && !isSyncing) {
			syncQueue()
		}
	}, [isOnline, queue.length, isSyncing, syncQueue])

	return { queue, isOnline, isSyncing, enqueue: enqueueMutation, syncQueue, refreshQueue }
}
