// Generated by Muse Spark 1.2 on 2026-08-31
import { projectApi } from "../services/api"
import { useApi } from "./useApi"

export const useProjects = (options = {}) => useApi(projectApi.getProjects, { initialData: [], ...options })
