// Generated by Muse Spark on 2026-09-12
import { render, screen, waitFor } from "@testing-library/react"
import userEvent from "@testing-library/user-event"
import { beforeEach, describe, expect, it, vi } from "vitest"
import { Router } from "wouter"
import { memoryLocation } from "wouter/memory-location"
import { AuthPage } from "./AuthPage"

const { mockCreateUser, mockLogin } = vi.hoisted(() => ({
	mockCreateUser: vi.fn(),
	mockLogin: vi.fn(),
}))

vi.mock("../services/api", () => ({
	userApi: {
		createUser: mockCreateUser,
	},
	authApi: {
		login: mockLogin,
		logout: vi.fn(),
		getStatus: vi.fn(),
	},
	projectApi: { getProjects: vi.fn() },
	taskApi: { getTasks: vi.fn() },
}))

const renderPage = (path = "/register") => {
	const location = memoryLocation({ path, record: true })
	render(
		<Router hook={location.hook}>
			<AuthPage />
		</Router>,
	)
	return location
}

beforeEach(() => {
	localStorage.clear()
	mockCreateUser.mockReset()
	mockLogin.mockReset()
})

describe("AuthPage", () => {
	it("renders sign-in mode by default with a mode toggle", () => {
		renderPage()

		expect(screen.getByRole("heading", { name: "Welcome back" })).toBeInTheDocument()
		expect(screen.getByRole("group", { name: "Authentication mode" })).toBeInTheDocument()
		expect(screen.getByRole("button", { name: "Sign In" })).toHaveAttribute("aria-pressed", "true")
		expect(screen.getByRole("button", { name: "Sign Up" })).toBeInTheDocument()
	})

	it("toggles to sign-up mode and resets errors", async () => {
		const user = userEvent.setup()
		renderPage()

		await user.click(screen.getByRole("button", { name: "Sign Up" }))

		expect(screen.getByRole("heading", { name: "Create your account" })).toBeInTheDocument()
		expect(screen.getByLabelText("Confirm password")).toBeInTheDocument()
		expect(screen.getByRole("button", { name: "Sign Up" })).toHaveAttribute("aria-pressed", "true")
	})

	it("signs up successfully and shows a status message", async () => {
		const user = userEvent.setup()
		mockCreateUser.mockResolvedValue({ id: 3, username: "newuser" })
		renderPage()

		await user.click(screen.getByRole("button", { name: "Sign Up" }))
		await user.type(screen.getByLabelText("Username"), "newuser")
		await user.type(screen.getByLabelText("Password"), "password123")
		await user.type(screen.getByLabelText("Confirm password"), "password123")
		await user.click(screen.getByRole("button", { name: "Sign up" }))

		expect(await screen.findByRole("status")).toHaveTextContent("Welcome, newuser!")
		expect(mockCreateUser).toHaveBeenCalledWith({ username: "newuser", password: "password123" })
		expect(JSON.parse(localStorage.getItem("task-tracker:auth-user"))).toEqual({ id: 3, username: "newuser", password: "password123" })
	})

	it("surfaces duplicate-username failures in an alert", async () => {
		const user = userEvent.setup()
		const err = new Error("Request failed with status 400")
		err.status = 400
		err.body = { username: ["A user with that username already exists."] }
		mockCreateUser.mockRejectedValue(err)
		renderPage()

		await user.click(screen.getByRole("button", { name: "Sign Up" }))
		await user.type(screen.getByLabelText("Username"), "maya")
		await user.type(screen.getByLabelText("Password"), "password123")
		await user.type(screen.getByLabelText("Confirm password"), "password123")
		await user.click(screen.getByRole("button", { name: "Sign up" }))

		expect(await screen.findByRole("alert")).toHaveTextContent("A user with that username already exists.")
	})

	it("signs in against the backend login endpoint and redirects to the board", async () => {
		const user = userEvent.setup()
		mockLogin.mockResolvedValue({ id: 2, username: "maya" })
		const location = renderPage()

		await user.type(screen.getByLabelText("Username"), "maya")
		await user.type(screen.getByLabelText("Password"), "correct-password")
		await user.click(screen.getByRole("button", { name: "Sign in" }))

		expect(mockLogin).toHaveBeenCalledWith({ username: "maya", password: "correct-password" })
		await waitFor(() => expect(location.history.at(-1)).toBe("/"))
	})

	it("rejects wrong sign-in passwords", async () => {
		const user = userEvent.setup()
		const err = new Error("Invalid username or password.")
		err.status = 400
		mockLogin.mockRejectedValue(err)
		renderPage()

		await user.type(screen.getByLabelText("Username"), "maya")
		await user.type(screen.getByLabelText("Password"), "wrong-password")
		await user.click(screen.getByRole("button", { name: "Sign in" }))

		expect(await screen.findByRole("alert")).toHaveTextContent("Invalid username or password.")
	})

	it("signs in offline with a known user when the backend is unreachable", async () => {
		const user = userEvent.setup()
		mockLogin.mockRejectedValue(new TypeError("Failed to fetch"))
		const location = renderPage()

		await user.type(screen.getByLabelText("Username"), "Admin")
		await user.type(screen.getByLabelText("Password"), "any-password")
		await user.click(screen.getByRole("button", { name: "Sign in" }))

		await waitFor(() => expect(location.history.at(-1)).toBe("/"))
	})

	it("rejects unknown sign-in usernames", async () => {
		const user = userEvent.setup()
		mockLogin.mockRejectedValue(new TypeError("Failed to fetch"))
		renderPage()

		await user.type(screen.getByLabelText("Username"), "ghost")
		await user.type(screen.getByLabelText("Password"), "any-password")
		await user.click(screen.getByRole("button", { name: "Sign in" }))

		expect(await screen.findByRole("alert")).toHaveTextContent("Invalid username or password.")
	})
})
