// Generated by Muse Spark on 2026-09-12
import { useState } from "react"
import { useLocation } from "wouter"
import { AuthForm } from "../components/AuthForm"
import { getSessionUser, signIn, signUp } from "../services/authService"

const extractErrorMessage = (err, fallback) => {
	const body = err?.body
	if (body && typeof body === "object") {
		const first = body.username?.[0] ?? body.password?.[0] ?? body.detail ?? body.message
		if (typeof first === "string" && first) return first
	}
	if (typeof err?.message === "string" && err.message) return err.message
	return fallback
}

export const AuthPage = () => {
	const [, navigate] = useLocation()
	const [mode, setMode] = useState("signin")
	const [isSubmitting, setIsSubmitting] = useState(false)
	const [serverError, setServerError] = useState("")
	const [success, setSuccess] = useState("")
	const [sessionUser, setSessionUserState] = useState(() => getSessionUser())
	const isSignup = mode === "signup"

	const handleModeChange = (next) => {
		setMode(next)
		setServerError("")
		setSuccess("")
	}

	const handleSubmit = async ({ username, password }) => {
		setIsSubmitting(true)
		setServerError("")
		setSuccess("")
		try {
			if (isSignup) {
				const session = await signUp({ username, password })
				setSessionUserState(session)
				setSuccess(`Welcome, ${session.username}! Your account was created.`)
			} else {
				const session = await signIn({ username, password })
				setSessionUserState(session)
				setSuccess(`Welcome back, ${session.username}!`)
			}
		} catch (err) {
			setServerError(extractErrorMessage(err, isSignup ? "Sign up failed." : "Invalid username or password."))
			return
		} finally {
			setIsSubmitting(false)
		}
		if (!isSignup) navigate("/")
	}

	return (
		<main className="auth-page">
			<div className="auth-card">
				<h2 className="projects-page-title">{isSignup ? "Create your account" : "Welcome back"}</h2>
				<p className="projects-page-subtitle">{isSignup ? "Sign up to start tracking tasks" : "Sign in to continue"}</p>
				<fieldset className="auth-tabs">
					<legend className="sr-only">Authentication mode</legend>
					<button type="button" className="btn btn-secondary" aria-pressed={!isSignup} onClick={() => handleModeChange("signin")}>
						Sign In
					</button>
					<button type="button" className="btn btn-secondary" aria-pressed={isSignup} onClick={() => handleModeChange("signup")}>
						Sign Up
					</button>
				</fieldset>
				{sessionUser && (
					<p className="projects-page-subtitle">
						Signed in as <strong>{sessionUser.username}</strong>
					</p>
				)}
				<AuthForm mode={mode} onSubmit={handleSubmit} isSubmitting={isSubmitting} serverError={serverError} />
				{success && <output className="auth-success">{success}</output>}
			</div>
		</main>
	)
}
