// Generated by Claude Opus 4.6 on 2026-08-29
import { useCallback, useEffect, useState } from "react"
import { Link } from "wouter"
import { ConfirmDialog } from "../components/ConfirmDialog"
import { CreateProjectForm } from "../components/CreateProjectForm"
import { ProjectList } from "../components/ProjectList"
import { useOfflineQueueContext } from "../context/OfflineQueueContext"
import { projectApi } from "../services/api"
import { API_BASE_URL } from "../utils/apiClient"
import { isNetworkError } from "../utils/offlineQueue"

export const ProjectsPage = ({ onProjectsRefresh }) => {
	const [projects, setProjects] = useState([])
	const [loading, setLoading] = useState(true)
	const [error, setError] = useState("")
	const [confirmProjectId, setConfirmProjectId] = useState(null)
	const { enqueue } = useOfflineQueueContext()

	const fetchProjects = useCallback(async () => {
		try {
			setLoading(true)
			setError("")
			setProjects(await projectApi.getProjects())
		} catch {
			setError("Projects could not be loaded.")
		} finally {
			setLoading(false)
		}
	}, [])

	useEffect(() => {
		fetchProjects()
	}, [fetchProjects])

	const handleCreate = async (name) => {
		const tempId = Date.now()
		try {
			const project = await projectApi.createProject(name)
			setProjects((current) => [...current, project])
			if (onProjectsRefresh) onProjectsRefresh()
			return project
		} catch (err) {
			if (!navigator.onLine || isNetworkError(err)) {
				const tempProject = { id: tempId, name }
				setProjects((current) => [...current, tempProject])
				if (onProjectsRefresh) onProjectsRefresh()
				enqueue({
					method: "POST",
					url: `${API_BASE_URL}/projects/`,
					body: { name },
					meta: { entity: "project", action: "create", clientId: tempId },
				})
				return tempProject
			}
			setError("Project could not be created.")
			return null
		}
	}

	const handleDelete = (projectId) => {
		setConfirmProjectId(projectId)
	}

	const handleConfirmDelete = async () => {
		const id = confirmProjectId
		setConfirmProjectId(null)
		try {
			await projectApi.deleteProject(id)
			setProjects((current) => current.filter((p) => p.id !== id))
			if (onProjectsRefresh) onProjectsRefresh()
		} catch (err) {
			if (!navigator.onLine || isNetworkError(err)) {
				setProjects((current) => current.filter((p) => p.id !== id))
				if (onProjectsRefresh) onProjectsRefresh()
				enqueue({
					method: "DELETE",
					url: `${API_BASE_URL}/projects/${id}/`,
					body: null,
					meta: { entity: "project", action: "delete", originalTaskId: id },
				})
			} else {
				setError("Project could not be deleted.")
			}
		}
	}

	const handleCancelDelete = () => setConfirmProjectId(null)

	return (
		<div className="projects-page">
			<div className="projects-page-header">
				<div>
					<h2 className="projects-page-title">Projects</h2>
					<p className="projects-page-subtitle">Create and manage your projects</p>
				</div>
				<Link href="/" className="btn btn-secondary">
					← Back to Board
				</Link>
			</div>

			<CreateProjectForm onCreate={handleCreate} />

			{loading && <p className="project-message">Loading projects...</p>}
			{error && (
				<div className="project-message project-error" role="alert">
					<span>{error}</span>
					<button type="button" className="btn btn-secondary" onClick={fetchProjects}>
						Retry
					</button>
				</div>
			)}
			{!loading && !error && <ProjectList projects={projects} onDelete={handleDelete} />}
			<ConfirmDialog
				isOpen={confirmProjectId !== null}
				title="Delete project?"
				message="Delete this project? Tasks will be preserved."
				confirmLabel="Delete"
				cancelLabel="Cancel"
				variant="danger"
				onConfirm={handleConfirmDelete}
				onCancel={handleCancelDelete}
			/>
		</div>
	)
}
