// Generated by Gemini 3.6 Flash on 2026-09-06
import { render, screen, waitFor } from "@testing-library/react"
import userEvent from "@testing-library/user-event"
import { beforeEach, describe, expect, it, vi } from "vitest"
import { Router } from "wouter"
import { memoryLocation } from "wouter/memory-location"
import { OfflineQueueProvider } from "../context/OfflineQueueContext"
import { projectApi } from "../services/api"
import { ProjectsPage } from "./ProjectsPage"

vi.mock("../services/api", () => ({
	projectApi: {
		getProjects: vi.fn(),
		createProject: vi.fn(),
		deleteProject: vi.fn(),
	},
}))

const projects = [
	{ id: 12, name: "Website refresh" },
	{ id: 13, name: "Mobile app" },
]

const renderProjectsPage = () => {
	const location = memoryLocation({ path: "/projects" })
	return render(
		<Router hook={location.hook}>
			<OfflineQueueProvider>
				<ProjectsPage />
			</OfflineQueueProvider>
		</Router>,
	)
}

describe("ProjectsPage", () => {
	beforeEach(() => {
		vi.resetAllMocks()
		localStorage.clear()
		Object.defineProperty(navigator, "onLine", { configurable: true, value: true })
	})

	it("shows an initial loading message", () => {
		projectApi.getProjects.mockReturnValue(new Promise(() => {}))
		renderProjectsPage()

		expect(screen.getByText("Loading projects...")).toBeInTheDocument()
	})

	it("renders projects returned by the API", async () => {
		projectApi.getProjects.mockResolvedValue(projects)
		renderProjectsPage()

		expect(await screen.findByText("Website refresh")).toBeInTheDocument()
		expect(screen.getByText("Mobile app")).toBeInTheDocument()
	})

	it("offers a retry after a loading error", async () => {
		const user = userEvent.setup()
		projectApi.getProjects.mockRejectedValueOnce(new Error("Unavailable")).mockResolvedValueOnce(projects)
		renderProjectsPage()

		expect(await screen.findByRole("alert")).toHaveTextContent("Projects could not be loaded.")
		await user.click(screen.getByRole("button", { name: "Retry" }))

		expect(await screen.findByText("Website refresh")).toBeInTheDocument()
		expect(projectApi.getProjects).toHaveBeenCalledTimes(2)
	})

	it("creates a project and displays it", async () => {
		const user = userEvent.setup()
		projectApi.getProjects.mockResolvedValue(projects)
		projectApi.createProject.mockResolvedValue({ id: 14, name: "Documentation" })
		renderProjectsPage()

		await screen.findByText("Website refresh")
		await user.type(screen.getByLabelText("Project name"), "Documentation")
		await user.click(screen.getByRole("button", { name: "Add project" }))

		await waitFor(() => expect(projectApi.createProject).toHaveBeenCalledWith("Documentation"))
		expect(await screen.findByText("Documentation")).toBeInTheDocument()
	})

	it("deletes a project only after deletion is confirmed", async () => {
		const user = userEvent.setup()
		projectApi.getProjects.mockResolvedValue(projects)
		projectApi.deleteProject.mockResolvedValue(true)
		renderProjectsPage()

		await screen.findByText("Website refresh")
		await user.click(screen.getByRole("button", { name: "Delete Website refresh" }))
		expect(projectApi.deleteProject).not.toHaveBeenCalled()

		await user.click(screen.getByRole("button", { name: /^Delete$/ }))
		await waitFor(() => expect(projectApi.deleteProject).toHaveBeenCalledWith(12))
		await waitFor(() => expect(screen.queryByText("Website refresh")).not.toBeInTheDocument())
	})
})
