// Generated by Claude Opus 4.6 on 2026-08-29
import { useCallback, useEffect, useState } from "react"
import { Link } from "wouter"
import { CreateProjectForm } from "../components/CreateProjectForm"
import { ProjectList } from "../components/ProjectList"
import { projectApi } from "../services/api"

export const ProjectsPage = ({ onProjectsRefresh }) => {
	const [projects, setProjects] = useState([])
	const [loading, setLoading] = useState(true)
	const [error, setError] = useState("")

	const fetchProjects = useCallback(async () => {
		try {
			setLoading(true)
			setError("")
			setProjects(await projectApi.getProjects())
		} catch {
			setError("Projects could not be loaded.")
		} finally {
			setLoading(false)
		}
	}, [])

	useEffect(() => {
		fetchProjects()
	}, [fetchProjects])

	const handleCreate = async (name) => {
		try {
			const project = await projectApi.createProject(name)
			setProjects((current) => [...current, project])
			if (onProjectsRefresh) onProjectsRefresh()
			return project
		} catch {
			setError("Project could not be created.")
			return null
		}
	}

	const handleDelete = async (projectId) => {
		if (!window.confirm("Delete this project? Tasks will be preserved.")) return
		try {
			await projectApi.deleteProject(projectId)
			setProjects((current) => current.filter((p) => p.id !== projectId))
			if (onProjectsRefresh) onProjectsRefresh()
		} catch {
			setError("Project could not be deleted.")
		}
	}

	return (
		<div className="projects-page">
			<div className="projects-page-header">
				<div>
					<h2 className="projects-page-title">Projects</h2>
					<p className="projects-page-subtitle">Create and manage your projects</p>
				</div>
				<Link href="/" className="btn btn-secondary">
					← Back to Board
				</Link>
			</div>

			<CreateProjectForm onCreate={handleCreate} />

			{loading && <p className="project-message">Loading projects...</p>}
			{error && (
				<div className="project-message project-error" role="alert">
					<span>{error}</span>
					<button type="button" className="btn btn-secondary" onClick={fetchProjects}>
						Retry
					</button>
				</div>
			)}
			{!loading && !error && <ProjectList projects={projects} onDelete={handleDelete} />}
		</div>
	)
}
