// Generated by Muse Spark on 2026-09-12
import { render, screen, waitFor } from "@testing-library/react"
import userEvent from "@testing-library/user-event"
import { beforeEach, describe, expect, it, vi } from "vitest"
import { Router } from "wouter"
import { memoryLocation } from "wouter/memory-location"
import { ThemeProvider } from "../context/ThemeContext"
import { systemApi } from "../services/api"
import { API_BASE_URL_STORAGE_KEY, DEFAULT_API_BASE_URL } from "../utils/apiClient"
import { SettingsPage } from "./SettingsPage"

vi.mock("../services/api", () => ({
	systemApi: {
		checkHealth: vi.fn(),
	},
}))

const renderSettingsPage = () => {
	const location = memoryLocation({ path: "/settings" })
	return render(
		<Router hook={location.hook}>
			<ThemeProvider>
				<SettingsPage />
			</ThemeProvider>
		</Router>,
	)
}

describe("SettingsPage", () => {
	beforeEach(() => {
		vi.resetAllMocks()
		localStorage.clear()
	})

	it("renders the current URL and probes on mount", async () => {
		systemApi.checkHealth.mockResolvedValue(true)
		renderSettingsPage()

		expect(screen.getByLabelText("API base URL")).toHaveValue(DEFAULT_API_BASE_URL)
		expect(systemApi.checkHealth).toHaveBeenCalledTimes(1)
		expect(await screen.findByText("Online")).toBeInTheDocument()
	})

	it("shows a checking state while the probe is pending", () => {
		systemApi.checkHealth.mockReturnValue(new Promise(() => {}))
		renderSettingsPage()

		expect(screen.getByRole("status")).toHaveTextContent("Checking…")
	})

	it("shows offline state and re-probes on Retry", async () => {
		const user = userEvent.setup()
		systemApi.checkHealth.mockResolvedValue(false)
		renderSettingsPage()

		expect(await screen.findByText(/Offline — backend unreachable/)).toBeInTheDocument()
		expect(screen.getByText(/Last checked:/)).toBeInTheDocument()

		await user.click(screen.getByRole("button", { name: "Retry" }))

		await waitFor(() => expect(systemApi.checkHealth).toHaveBeenCalledTimes(2))
	})

	it("saves a valid URL and re-probes", async () => {
		const user = userEvent.setup()
		systemApi.checkHealth.mockResolvedValue(true)
		renderSettingsPage()

		await screen.findByText("Online")
		const input = screen.getByLabelText("API base URL")
		await user.clear(input)
		await user.type(input, "https://api.example.com/api")
		await user.click(screen.getByRole("button", { name: "Save" }))

		expect(localStorage.getItem(API_BASE_URL_STORAGE_KEY)).toBe("https://api.example.com/api")
		await waitFor(() => expect(systemApi.checkHealth).toHaveBeenCalledTimes(2))
		expect(await screen.findByText("Online")).toBeInTheDocument()
	})

	it("rejects an invalid URL without saving or re-probing", async () => {
		const user = userEvent.setup()
		systemApi.checkHealth.mockResolvedValue(true)
		renderSettingsPage()

		await screen.findByText("Online")
		const input = screen.getByLabelText("API base URL")
		await user.clear(input)
		await user.type(input, "not a url")
		await user.click(screen.getByRole("button", { name: "Save" }))

		expect(await screen.findByRole("alert")).toHaveTextContent("Enter a valid API base URL")
		expect(localStorage.getItem(API_BASE_URL_STORAGE_KEY)).toBeNull()
		expect(systemApi.checkHealth).toHaveBeenCalledTimes(1)
	})

	it("resets to the default URL and re-probes", async () => {
		const user = userEvent.setup()
		localStorage.setItem(API_BASE_URL_STORAGE_KEY, "https://custom.example.com/api")
		systemApi.checkHealth.mockResolvedValue(true)
		renderSettingsPage()

		expect(screen.getByLabelText("API base URL")).toHaveValue("https://custom.example.com/api")
		await user.click(screen.getByRole("button", { name: "Reset to default" }))

		expect(screen.getByLabelText("API base URL")).toHaveValue(DEFAULT_API_BASE_URL)
		expect(localStorage.getItem(API_BASE_URL_STORAGE_KEY)).toBeNull()
		await waitFor(() => expect(systemApi.checkHealth).toHaveBeenCalledTimes(2))
	})

	it("switches between light and dark modes", async () => {
		const user = userEvent.setup()
		systemApi.checkHealth.mockResolvedValue(true)
		renderSettingsPage()

		const lightButton = screen.getByRole("button", { name: "Light" })
		const darkButton = screen.getByRole("button", { name: "Dark" })

		await user.click(darkButton)
		expect(darkButton).toHaveAttribute("aria-pressed", "true")
		expect(localStorage.getItem("task-tracker-theme")).toBe("dark")

		await user.click(lightButton)
		expect(lightButton).toHaveAttribute("aria-pressed", "true")
		expect(localStorage.getItem("task-tracker-theme")).toBe("light")
	})
})
