// Generated by Muse Spark on 2026-09-12
import { ChevronDown, ChevronUp, Moon, RotateCcw, Sun } from "lucide-react"
import { useCallback, useEffect, useRef, useState } from "react"
import { Link } from "wouter"
import { ApiStatusBadge } from "../components/ApiStatusBadge"
import { useTheme } from "../context/ThemeContext"
import { systemApi } from "../services/api"
import { DEFAULT_API_BASE_URL, getApiBaseUrl, isValidApiBaseUrl, resetApiBaseUrl, setApiBaseUrl } from "../utils/apiClient"
import { useColumnConfig } from "../utils/columnConfig"

export const SettingsPage = () => {
	const { theme, setTheme } = useTheme()
	const [inputValue, setInputValue] = useState(() => getApiBaseUrl())
	const [validationError, setValidationError] = useState("")
	const [status, setStatus] = useState("checking")
	const [checkedUrl, setCheckedUrl] = useState(() => getApiBaseUrl())
	const [lastChecked, setLastChecked] = useState(null)
	const probeIdRef = useRef(0)
	const [columns, saveColumns, resetColumns] = useColumnConfig()
	const [draftTitles, setDraftTitles] = useState(() => Object.fromEntries(columns.map((column) => [column.id, column.title])))
	const [isColumnsOpen, setIsColumnsOpen] = useState(true)

	const probe = useCallback(async () => {
		const probeId = probeIdRef.current + 1
		probeIdRef.current = probeId
		const url = getApiBaseUrl()
		setCheckedUrl(url)
		setStatus("checking")
		const online = await systemApi.checkHealth()
		if (probeIdRef.current !== probeId) return // Superseded by a newer probe
		setStatus(online ? "online" : "offline")
		setLastChecked(new Date())
	}, [])

	useEffect(() => {
		probe()
		return () => {
			probeIdRef.current += 1 // Abort (ignore) in-flight probe on unmount
		}
	}, [probe])

	const handleSave = (event) => {
		event.preventDefault()
		const value = inputValue.trim()
		if (!isValidApiBaseUrl(value)) {
			setValidationError("Enter a valid API base URL starting with /, http://, or https:// (no spaces).")
			return
		}
		setValidationError("")
		setApiBaseUrl(value)
		setInputValue(value)
		probe()
	}

	const handleReset = () => {
		resetApiBaseUrl()
		setValidationError("")
		setInputValue(DEFAULT_API_BASE_URL)
		probe()
	}

	const updateColumn = (id, updates) => {
		saveColumns(columns.map((column) => (column.id === id ? { ...column, ...updates } : column)))
	}

	const handleColumnTitleChange = (id, title) => {
		setDraftTitles((current) => ({ ...current, [id]: title }))
		if (title.trim()) updateColumn(id, { title: title.trim() })
	}

	const handleResetColumns = () => {
		const defaults = resetColumns()
		setDraftTitles(Object.fromEntries(defaults.map((column) => [column.id, column.title])))
	}

	const moveColumn = (id, direction) => {
		const currentIndex = columns.findIndex((column) => column.id === id)
		const nextIndex = currentIndex + direction
		if (currentIndex < 0 || nextIndex < 0 || nextIndex >= columns.length) return
		const nextColumns = [...columns]
		const currentColumn = nextColumns[currentIndex]
		nextColumns[currentIndex] = nextColumns[nextIndex]
		nextColumns[nextIndex] = currentColumn
		saveColumns(nextColumns)
	}

	const visibleColumnCount = columns.filter((column) => column.visible).length

	return (
		<div className="projects-page">
			<div className="projects-page-header">
				<div>
					<h2 className="projects-page-title">Settings</h2>
					<p className="projects-page-subtitle">Configure how the app connects to the backend</p>
				</div>
				<Link href="/" className="btn btn-secondary">
					← Back to Board
				</Link>
			</div>

			<section className="settings-card" aria-label="Appearance settings">
				<div>
					<h3 className="settings-section-title">Appearance</h3>
					<p className="form-help">Choose how Task Tracker looks. Your choice is saved on this device.</p>
				</div>
				<fieldset className="settings-theme-options">
					<legend className="sr-only">Color theme</legend>
					<button
						type="button"
						className={`btn ${theme === "light" ? "btn-primary" : "btn-secondary"}`}
						aria-pressed={theme === "light"}
						onClick={() => setTheme("light")}
					>
						<Sun size={18} />
						<span>Light</span>
					</button>
					<button
						type="button"
						className={`btn ${theme === "dark" ? "btn-primary" : "btn-secondary"}`}
						aria-pressed={theme === "dark"}
						onClick={() => setTheme("dark")}
					>
						<Moon size={18} />
						<span>Dark</span>
					</button>
				</fieldset>
				<p className="form-help" aria-live="polite">
					Current theme: {theme === "dark" ? "Dark" : "Light"}
				</p>
			</section>

			<section className="settings-card settings-columns-card" aria-label="Board columns settings">
				<button
					type="button"
					className="settings-section-toggle"
					aria-expanded={isColumnsOpen}
					aria-controls="board-columns-content"
					onClick={() => setIsColumnsOpen((open) => !open)}
				>
					<span>
						<strong className="settings-section-title">Board columns</strong>
						<span className="form-help">Rename, reorder, or hide the supported task statuses.</span>
					</span>
					<ChevronDown size={18} className={`settings-section-chevron${isColumnsOpen ? " is-open" : ""}`} aria-hidden="true" />
				</button>
				{isColumnsOpen && (
					<div id="board-columns-content" className="settings-columns-content">
						<div className="settings-column-list">
							{columns.map((column, index) => (
								<div className="settings-column-row" key={column.id}>
									<div className="settings-column-main">
										<span className="settings-column-id">{column.id}</span>
										<label className="settings-column-label" htmlFor={`column-title-${column.id}`}>
											<span className="sr-only">Display name</span>
											<input
												id={`column-title-${column.id}`}
												className="form-input"
												aria-label={`Column name for ${column.id}`}
												value={draftTitles[column.id] ?? column.title}
												onChange={(event) => handleColumnTitleChange(column.id, event.target.value)}
											/>
										</label>
									</div>
									<div className="settings-column-actions">
										<label className="settings-column-visibility">
											<input
												type="checkbox"
												checked={column.visible}
												disabled={column.visible && visibleColumnCount === 1}
												onChange={(event) => updateColumn(column.id, { visible: event.target.checked })}
											/>
											<span>Show</span>
										</label>
										<button
											type="button"
											className="btn btn-icon"
											title="Move column up"
											aria-label={`Move ${column.title} up`}
											disabled={index === 0}
											onClick={() => moveColumn(column.id, -1)}
										>
											<ChevronUp size={16} />
										</button>
										<button
											type="button"
											className="btn btn-icon"
											title="Move column down"
											aria-label={`Move ${column.title} down`}
											disabled={index === columns.length - 1}
											onClick={() => moveColumn(column.id, 1)}
										>
											<ChevronDown size={16} />
										</button>
									</div>
								</div>
							))}
						</div>
						<button type="button" className="btn btn-secondary" onClick={handleResetColumns}>
							<RotateCcw size={16} />
							<span>Reset columns</span>
						</button>
					</div>
				)}
			</section>

			<section className="settings-card" aria-label="API settings">
				<form className="settings-form" onSubmit={handleSave}>
					<div className="form-group">
						<label className="form-label" htmlFor="api-base-url">
							API base URL
						</label>
						<input
							id="api-base-url"
							type="text"
							className="form-input"
							value={inputValue}
							onChange={(event) => setInputValue(event.target.value)}
							placeholder={DEFAULT_API_BASE_URL}
							spellCheck={false}
							autoComplete="off"
						/>
						<p className="form-help">Backend API base URL. Use a path like /api or a full origin like https://api.example.com/api.</p>
						{validationError && (
							<p className="form-error" role="alert">
								{validationError}
							</p>
						)}
					</div>
					<div className="settings-form-row">
						<button type="submit" className="btn btn-primary">
							Save
						</button>
						<button type="button" className="btn btn-secondary" onClick={handleReset}>
							Reset to default
						</button>
					</div>
				</form>

				<ApiStatusBadge status={status} checkedUrl={checkedUrl} lastChecked={lastChecked} onRetry={probe} />
			</section>
		</div>
	)
}
