# Generated by Gemini 3.6 Flash on 2026-08-19
from django.db import migrations, models


class Migration(migrations.Migration):
	initial = True

	dependencies = []

	operations = [
		migrations.CreateModel(
			name="Task",
			fields=[
				("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
				("title", models.CharField(max_length=255)),
				("description", models.TextField(blank=True, default="")),
				(
					"status",
					models.CharField(
						choices=[("TODO", "To Do"), ("IN_PROGRESS", "In Progress"), ("REVIEW", "Review"), ("DONE", "Done")], default="TODO", max_length=20
					),
				),
				("priority", models.CharField(choices=[("LOW", "Low"), ("MEDIUM", "Medium"), ("HIGH", "High")], default="MEDIUM", max_length=10)),
				("assignee", models.CharField(default="Admin", max_length=100)),
				("created_at", models.DateTimeField(auto_now_add=True)),
				("updated_at", models.DateTimeField(auto_now=True)),
			],
			options={
				"ordering": ["-created_at"],
			},
		),
	]
