# Generated by GitHub Copilot on 2026-08-25

from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		("tasks", "0001_initial"),
	]

	operations = [
		migrations.CreateModel(
			name="Project",
			fields=[
				("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
				("name", models.CharField(max_length=255, unique=True)),
				("created_at", models.DateTimeField(auto_now_add=True)),
				("updated_at", models.DateTimeField(auto_now=True)),
			],
			options={
				"ordering": ["-created_at"],
			},
		),
		migrations.AddField(
			model_name="task",
			name="projects",
			field=models.ManyToManyField(blank=True, related_name="tasks", to="tasks.project"),
		),
	]
