# Generated by Django 6.1 on 2026-08-27 21:30

from django.db import migrations


from django.contrib.auth.hashers import make_password

def migrate_assignees(apps, schema_editor):
    Task = apps.get_model('tasks', 'Task')
    User = apps.get_model('auth', 'User')

    # Ensure Admin user exists
    admin_user, _ = User.objects.get_or_create(username='Admin')
    if not admin_user.password:
        admin_user.password = make_password(None)
        admin_user.save()

    for task in Task.objects.all():
        if task.old_assignee:
            user, created = User.objects.get_or_create(username=task.old_assignee)
            if created:
                user.password = make_password(None)
                user.save()
            task.assignee = user
        else:
            task.assignee = admin_user
        task.save()


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_task_options_task_old_assignee_task_position_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_assignees),
        migrations.RemoveField(
            model_name='task',
            name='old_assignee',
        ),
    ]
