// Generated by Muse Spark 1.2 on 2026-08-31
import { createContext, useContext } from "react"
import { useOfflineQueue } from "../hooks/useOfflineQueue"

const OfflineQueueContext = createContext(null)

export const OfflineQueueProvider = ({ children }) => {
	const value = useOfflineQueue()
	return <OfflineQueueContext.Provider value={value}>{children}</OfflineQueueContext.Provider>
}

export const useOfflineQueueContext = () => {
	const ctx = useContext(OfflineQueueContext)
	if (!ctx) return { queue: [], isOnline: true, isSyncing: false, enqueue: null, syncQueue: async () => {}, refreshQueue: () => {} }
	return ctx
}
