// Generated by Muse Spark 1.2 on 2026-08-31
export const DEFAULT_API_BASE_URL = import.meta.env.VITE_API_BASE_URL || "/api"

// Kept for backward compat; prefer getApiBaseUrl() which reflects stored overrides.
export const API_BASE_URL = DEFAULT_API_BASE_URL

export const API_BASE_URL_STORAGE_KEY = "task-tracker:api-base-url"

export const isValidApiBaseUrl = (url) => {
	if (typeof url !== "string") return false
	const value = url.trim()
	if (!value || /\s/.test(value)) return false
	return value.startsWith("/") || value.startsWith("http://") || value.startsWith("https://")
}

export const getApiBaseUrl = () => {
	try {
		const stored = localStorage.getItem(API_BASE_URL_STORAGE_KEY)
		if (stored && isValidApiBaseUrl(stored)) return stored.trim()
	} catch {
		// localStorage unavailable; fall through to default
	}
	return DEFAULT_API_BASE_URL
}

export const setApiBaseUrl = (url) => {
	const value = url.trim()
	if (!isValidApiBaseUrl(value)) throw new Error("Invalid API base URL")
	try {
		localStorage.setItem(API_BASE_URL_STORAGE_KEY, value)
	} catch {
		// Persist failure is non-fatal; runtime resolution still uses the default
	}
	return value
}

export const resetApiBaseUrl = () => {
	try {
		localStorage.removeItem(API_BASE_URL_STORAGE_KEY)
	} catch {
		// Ignore removal failures
	}
	return DEFAULT_API_BASE_URL
}

export const MIN_DELAY_MS = 20
export const MAX_DELAY_MS = 2000

export const getRandomDelay = () => Math.floor(Math.random() * (MAX_DELAY_MS - MIN_DELAY_MS + 1)) + MIN_DELAY_MS

export const sleep = (ms) => new Promise((resolve) => setTimeout(resolve, ms))

export class ApiError extends Error {
	constructor(message, status, body) {
		super(message)
		this.name = "ApiError"
		this.status = status
		this.body = body
	}
}

import { getSessionUser } from "../services/authService"

const buildBasicHeader = (session) => {
	if (!session?.username || !session?.password) return null
	try {
		return `Basic ${btoa(`${session.username}:${session.password}`)}`
	} catch {
		return null
	}
}

export const apiRequest = async (path, { method = "GET", body, headers = {}, signal, auth = true } = {}) => {
	// await sleep(getRandomDelay()) // Simulate network delay
	const url = `${getApiBaseUrl()}${path}`
	// Public endpoints (signup, login, health, auth status) skip credentials so
	// stale stored sessions can never block them with a 401/403.
	const session = auth ? getSessionUser() : null
	const basicHeader = buildBasicHeader(session)

	const options = {
		method,
		// Send session cookies (Django session auth) alongside Basic auth.
		credentials: "include",
		headers: {
			Accept: "application/json",
			...(basicHeader ? { Authorization: basicHeader } : {}),
			...headers,
		},
	}

	if (signal) options.signal = signal

	if (body !== undefined && body !== null) {
		options.headers["Content-Type"] = "application/json"
		options.body = JSON.stringify(body)
	}

	const response = await fetch(url, options)

	if (response.status === 204) {
		return null
	}

	const text = await response.text()
	let data = null
	if (text) {
		try {
			data = JSON.parse(text)
		} catch {
			data = text
		}
	}

	if (!response.ok) {
		const message = data?.detail || data?.message || `Request failed with status ${response.status}`
		throw new ApiError(message, response.status, data)
	}

	return data
}
