// Generated by Muse Spark 1.2 on 2026-08-31
export const API_BASE_URL = "http://127.0.0.1:8000/api"

export class ApiError extends Error {
	constructor(message, status, body) {
		super(message)
		this.name = "ApiError"
		this.status = status
		this.body = body
	}
}

export const apiRequest = async (path, { method = "GET", body, headers = {} } = {}) => {
	const url = `${API_BASE_URL}${path}`
	const options = {
		method,
		headers: {
			Accept: "application/json",
			...headers,
		},
	}

	if (body !== undefined && body !== null) {
		options.headers["Content-Type"] = "application/json"
		options.body = JSON.stringify(body)
	}

	const response = await fetch(url, options)

	if (response.status === 204) {
		return null
	}

	const text = await response.text()
	let data = null
	if (text) {
		try {
			data = JSON.parse(text)
		} catch {
			data = text
		}
	}

	if (!response.ok) {
		const message = data?.detail || data?.message || `Request failed with status ${response.status}`
		throw new ApiError(message, response.status, data)
	}

	return data
}
