// Generated by Gemini 3.6 Flash on 2026-09-16
import { useEffect, useState } from "react"
import { COLUMNS } from "./constants"

export const COLUMN_CONFIG_STORAGE_KEY = "task-tracker:column-config"
export const COLUMN_CONFIG_EVENT = "task-tracker:column-config-changed"

const withDefaults = (columns) =>
	columns.map((column, order) => ({
		...column,
		visible: column.visible !== false,
		order,
	}))

export const DEFAULT_COLUMN_CONFIG = withDefaults(COLUMNS)

const isValidColumn = (column) =>
	column &&
	typeof column.id === "string" &&
	typeof column.title === "string" &&
	column.title.trim().length > 0 &&
	typeof column.className === "string" &&
	typeof column.visible === "boolean"

export const normalizeColumnConfig = (value) => {
	if (!Array.isArray(value)) return DEFAULT_COLUMN_CONFIG
	const columns = value
		.filter(isValidColumn)
		.sort((left, right) => (left.order ?? 0) - (right.order ?? 0))
		.map((column, order) => ({ ...column, title: column.title.trim(), order }))
	if (columns.length === 0 || !columns.some((column) => column.visible)) return DEFAULT_COLUMN_CONFIG
	return columns
}

export const getColumnConfig = () => {
	try {
		const stored = localStorage.getItem(COLUMN_CONFIG_STORAGE_KEY)
		return stored ? normalizeColumnConfig(JSON.parse(stored)) : DEFAULT_COLUMN_CONFIG
	} catch {
		return DEFAULT_COLUMN_CONFIG
	}
}

export const setColumnConfig = (columns) => {
	const orderedColumns = columns.map((column, order) => ({ ...column, order }))
	const normalized = normalizeColumnConfig(orderedColumns)
	localStorage.setItem(COLUMN_CONFIG_STORAGE_KEY, JSON.stringify(normalized))
	window.dispatchEvent(new CustomEvent(COLUMN_CONFIG_EVENT, { detail: normalized }))
	return normalized
}

export const resetColumnConfig = () => {
	localStorage.removeItem(COLUMN_CONFIG_STORAGE_KEY)
	window.dispatchEvent(new CustomEvent(COLUMN_CONFIG_EVENT, { detail: DEFAULT_COLUMN_CONFIG }))
	return DEFAULT_COLUMN_CONFIG
}

export const useColumnConfig = () => {
	const [columns, setColumns] = useState(getColumnConfig)

	useEffect(() => {
		const handleChange = (event) => setColumns(normalizeColumnConfig(event.detail || getColumnConfig()))
		window.addEventListener(COLUMN_CONFIG_EVENT, handleChange)
		return () => window.removeEventListener(COLUMN_CONFIG_EVENT, handleChange)
	}, [])

	return [columns, setColumnConfig, resetColumnConfig]
}
