// Generated by Muse Spark 1.2 on 2026-08-31
export const COLUMNS = [
	{ id: "TODO", title: "To Do", className: "column-todo" },
	{ id: "IN_PROGRESS", title: "In Progress", className: "column-in_progress" },
	{ id: "REVIEW", title: "Review", className: "column-review" },
	{ id: "DONE", title: "Done", className: "column-done" },
]

export const TASK_STATUSES = COLUMNS.map((column) => column.id)

export const PRIORITIES = [
	{ id: "LOW", title: "Low", className: "badge-priority-low" },
	{ id: "MEDIUM", title: "Medium", className: "badge-priority-medium" },
	{ id: "HIGH", title: "High", className: "badge-priority-high" },
]

export const TASK_PRIORITIES = PRIORITIES.map((priority) => priority.id)

export const PROJECT_FILTER_EMPTY_LABEL = "No projects"
