// Generated by Muse Spark 1.2 on 2026-08-31
export const API_BASE_URL = "http://127.0.0.1:8000/api"

export const COLUMNS = [
	{ id: "TODO", title: "To Do", color: "var(--status-todo)" },
	{ id: "IN_PROGRESS", title: "In Progress", color: "var(--status-in_progress)" },
	{ id: "REVIEW", title: "Review", color: "var(--status-review)" },
	{ id: "DONE", title: "Done", color: "var(--status-done)" },
]

export const TASK_STATUSES = COLUMNS.map((column) => column.id)

export const PRIORITIES = [
	{ id: "LOW", title: "Low", className: "badge-priority-low" },
	{ id: "MEDIUM", title: "Medium", className: "badge-priority-medium" },
	{ id: "HIGH", title: "High", className: "badge-priority-high" },
]

export const TASK_PRIORITIES = PRIORITIES.map((priority) => priority.id)

export const PROJECT_FILTER_EMPTY_LABEL = "No projects"
