// Generated by Muse Spark 1.2 on 2026-08-31
export const STORAGE_KEY = "task-tracker-offline-queue"

export const isOnline = () => {
	if (typeof navigator === "undefined") return true
	return navigator.onLine
}

export const isNetworkError = (err) => {
	if (!err) return false
	const msg = err.message || ""
	return msg.includes("Failed to fetch") || err.name === "TypeError" || msg.includes("NetworkError") || msg.includes("fetch")
}

export const getQueue = () => {
	try {
		const raw = localStorage.getItem(STORAGE_KEY)
		if (!raw) return []
		const parsed = JSON.parse(raw)
		return Array.isArray(parsed) ? parsed : []
	} catch {
		try {
			localStorage.setItem(STORAGE_KEY, JSON.stringify([]))
		} catch {}
		return []
	}
}

export const setQueue = (queue) => {
	try {
		localStorage.setItem(STORAGE_KEY, JSON.stringify(queue))
	} catch {}
}

export const enqueue = (mutation) => {
	const queue = getQueue()
	const entry = {
		id: `m_${Date.now()}_${Math.random().toString(36).slice(2, 6)}`,
		createdAt: Date.now(),
		attempts: 0,
		...mutation,
	}
	queue.push(entry)
	setQueue(queue)
	return queue
}

export const dequeueById = (id) => {
	const queue = getQueue().filter((item) => item.id !== id)
	setQueue(queue)
	return queue
}

export const clearQueue = () => setQueue([])

export const peek = () => {
	const queue = getQueue()
	return queue.length > 0 ? queue[0] : null
}

export const shiftQueue = () => {
	const queue = getQueue()
	if (queue.length === 0) return null
	const head = queue.shift()
	setQueue(queue)
	return head
}

export const removeById = dequeueById
