// Generated by Muse Spark 1.2 on 2026-08-31
import { PRIORITIES } from "./constants"

export const withProjectDetails = (task, projectIds, projects) => ({
	...task,
	project_ids: projectIds,
	projects: projectIds.map((projectId) => projects.find((project) => project.id === projectId)).filter(Boolean),
})

export const getVisibleTasks = (tasks, enabledProjectIds) => {
	if (enabledProjectIds.length === 0) return tasks
	return tasks.filter((task) => (task.project_ids || task.projects?.map((project) => project.id) || []).some((id) => enabledProjectIds.includes(id)))
}

export const filterTasksByProject = getVisibleTasks

export const getPriorityBadgeClass = (priority) => {
	const priorityObj = PRIORITIES.find((p) => p.id === priority)
	return priorityObj ? priorityObj.className : PRIORITIES[1].className
}
