// Generated by Gemini 3.6 Flash on 2026-08-19
import { apiRequest } from "../utils/apiClient"

export const taskApi = {
	async getTasks() {
		return apiRequest("/tasks/")
	},

	async createTask(taskData) {
		return apiRequest("/tasks/", { method: "POST", body: taskData })
	},

	async updateTask(id, taskData) {
		return apiRequest(`/tasks/${id}/`, { method: "PATCH", body: taskData })
	},

	async deleteTask(id) {
		await apiRequest(`/tasks/${id}/`, { method: "DELETE" })
		return true
	},

	async reorderTask(id, targetStatus, targetTaskId) {
		return apiRequest(`/tasks/${id}/reorder/`, {
			method: "POST",
			body: { status: targetStatus, target_task_id: targetTaskId },
		})
	},
}

export const projectApi = {
	async getProjects() {
		return apiRequest("/projects/")
	},

	async createProject(name) {
		return apiRequest("/projects/", { method: "POST", body: { name } })
	},

	async deleteProject(id) {
		await apiRequest(`/projects/${id}/`, { method: "DELETE" })
		return true
	},
}

export const userApi = {
	async getUsers() {
		return apiRequest("/users/")
	},
}
