// Generated by Gemini 3.6 Flash on 2026-08-19
import { apiRequest } from "../utils/apiClient"

export const taskApi = {
	async getTasks() {
		return apiRequest("/tasks/")
	},

	async createTask(taskData) {
		return apiRequest("/tasks/", { method: "POST", body: taskData })
	},

	async updateTask(id, taskData) {
		return apiRequest(`/tasks/${id}/`, { method: "PATCH", body: taskData })
	},

	async deleteTask(id) {
		await apiRequest(`/tasks/${id}/`, { method: "DELETE" })
		return true
	},

	async reorderTask(id, targetStatus, targetTaskId) {
		return apiRequest(`/tasks/${id}/reorder/`, {
			method: "POST",
			body: { status: targetStatus, target_task_id: targetTaskId },
		})
	},
}

export const projectApi = {
	async getProjects() {
		return apiRequest("/projects/")
	},

	async createProject(name) {
		return apiRequest("/projects/", { method: "POST", body: { name } })
	},

	async deleteProject(id) {
		await apiRequest(`/projects/${id}/`, { method: "DELETE" })
		return true
	},
}

export const userApi = {
	async getUsers() {
		return apiRequest("/users/")
	},

	async createUser({ username, password }) {
		return apiRequest("/users/", { method: "POST", body: { username, password }, auth: false })
	},
}

export const authApi = {
	async login({ username, password }) {
		return apiRequest("/auth/login/", { method: "POST", body: { username, password }, auth: false })
	},

	async logout() {
		try {
			return await apiRequest("/auth/logout/", { method: "POST", auth: false })
		} catch {
			return null
		}
	},

	async getStatus() {
		return apiRequest("/auth/status/", { auth: false })
	},
}

export const systemApi = {
	// Probes GET /health/; resolves true only on HTTP 200 with { status: "ok" }.
	// Any network error, timeout, non-2xx, or invalid body resolves false (never throws).
	async checkHealth() {
		const controller = new AbortController()
		const timeoutId = setTimeout(() => controller.abort(), 5000)
		try {
			const data = await apiRequest("/health/", { signal: controller.signal, auth: false })
			return data?.status === "ok"
		} catch {
			return false
		} finally {
			clearTimeout(timeoutId)
		}
	},
}
