// Generated by Gemini 3.6 Flash on 2026-08-19

const API_BASE_URL = "http://127.0.0.1:8000/api"

export const taskApi = {
	async getTasks() {
		try {
			const response = await fetch(`${API_BASE_URL}/tasks/`)
			if (!response.ok) throw new Error("Failed to fetch tasks")
			return await response.json()
		} catch (error) {
			console.warn("Backend API connection warning, using local state fallback if needed:", error)
			throw error
		}
	},

	async createTask(taskData) {
		const response = await fetch(`${API_BASE_URL}/tasks/`, {
			method: "POST",
			headers: {
				"Content-Type": "application/json",
			},
			body: JSON.stringify(taskData),
		})
		if (!response.ok) throw new Error("Failed to create task")
		return await response.json()
	},

	async updateTask(id, taskData) {
		const response = await fetch(`${API_BASE_URL}/tasks/${id}/`, {
			method: "PATCH",
			headers: {
				"Content-Type": "application/json",
			},
			body: JSON.stringify(taskData),
		})
		if (!response.ok) throw new Error(`Failed to update task ${id}`)
		return await response.json()
	},

	async deleteTask(id) {
		const response = await fetch(`${API_BASE_URL}/tasks/${id}/`, {
			method: "DELETE",
		})
		if (!response.ok) throw new Error(`Failed to delete task ${id}`)
		return true
	},

	async reorderTask(id, targetStatus, targetTaskId) {
		const response = await fetch(`${API_BASE_URL}/tasks/${id}/reorder/`, {
			method: "POST",
			headers: {
				"Content-Type": "application/json",
			},
			body: JSON.stringify({
				status: targetStatus,
				target_task_id: targetTaskId,
			}),
		})
		if (!response.ok) throw new Error(`Failed to reorder task ${id}`)
		return await response.json()
	},
}

export const projectApi = {
	async getProjects() {
		const response = await fetch(`${API_BASE_URL}/projects/`)
		if (!response.ok) throw new Error("Failed to fetch projects")
		return await response.json()
	},

	async createProject(name) {
		const response = await fetch(`${API_BASE_URL}/projects/`, {
			method: "POST",
			headers: {
				"Content-Type": "application/json",
			},
			body: JSON.stringify({ name }),
		})
		if (!response.ok) throw new Error("Failed to create project")
		return await response.json()
	},

	async deleteProject(id) {
		const response = await fetch(`${API_BASE_URL}/projects/${id}/`, {
			method: "DELETE",
		})
		if (!response.ok) throw new Error(`Failed to delete project ${id}`)
		return true
	},
}

export const userApi = {
	async getUsers() {
		const response = await fetch(`${API_BASE_URL}/users/`)
		if (!response.ok) throw new Error("Failed to fetch users")
		return await response.json()
	},
}
