// Generated by Muse Spark on 2026-09-12
import { authApi, userApi } from "./api"

export const SESSION_KEY = "task-tracker:auth-user"

export const MOCK_USERS = [
	{ id: 1, username: "Admin" },
	{ id: 2, username: "maya" },
]

const readStored = () => {
	try {
		const raw = localStorage.getItem(SESSION_KEY)
		return raw ? JSON.parse(raw) : null
	} catch {
		return null
	}
}

export const getSessionUser = () => {
	const user = readStored()
	if (!user || typeof user.username !== "string") return null
	return user
}

export const setSessionUser = (user) => {
	if (!user) {
		localStorage.removeItem(SESSION_KEY)
		return
	}
	const session = { id: user.id ?? null, username: user.username }
	// Persist the password so API requests can authenticate with real Basic
	// credentials. Sessions stored before this change carry no password and
	// simply skip the Authorization header (relying on the session cookie).
	if (typeof user.password === "string" && user.password) session.password = user.password
	localStorage.setItem(SESSION_KEY, JSON.stringify(session))
}

export const signOut = () => {
	localStorage.removeItem(SESSION_KEY)
	// Best-effort server logout; never blocks the client sign-out.
	try {
		const pending = authApi.logout()
		if (pending?.catch) pending.catch(() => {})
	} catch {}
}

// Registers a new account, then signs in with the same credentials.
export const signUp = async ({ username, password }) => {
	const name = username.trim()
	if (!name || !password) throw new Error("Invalid username or password.")
	const created = await userApi.createUser({ username: name, password })
	const session = { id: created?.id ?? null, username: created?.username ?? name, password }
	setSessionUser(session)
	return session
}

// Verifies credentials against the backend login endpoint. Only genuine
// network failures fall back to the offline MOCK_USERS; HTTP error responses
// (unknown user, wrong password, auth required) always reject.
export const signIn = async ({ username, password }) => {
	const name = username.trim()
	if (!name || !password) throw new Error("Invalid username or password.")
	try {
		const data = await authApi.login({ username: name, password })
		const session = { id: data?.id ?? null, username: data?.username ?? name, password }
		setSessionUser(session)
		return session
	} catch (err) {
		if (err && typeof err.status === "number") throw new Error("Invalid username or password.")
		const match = MOCK_USERS.find((u) => u.username.toLowerCase() === name.toLowerCase())
		if (!match) throw new Error("Invalid username or password.")
		const session = { id: match.id ?? null, username: match.username }
		setSessionUser(session)
		return session
	}
}
