// Generated by Muse Spark on 2026-09-12
import { userApi } from "./api"

export const SESSION_KEY = "task-tracker:auth-user"

export const MOCK_USERS = [
	{ id: 1, username: "Admin" },
	{ id: 2, username: "maya" },
]

const readStored = () => {
	try {
		const raw = localStorage.getItem(SESSION_KEY)
		return raw ? JSON.parse(raw) : null
	} catch {
		return null
	}
}

export const getSessionUser = () => {
	const user = readStored()
	if (!user || typeof user.username !== "string") return null
	return user
}

export const setSessionUser = (user) => {
	if (!user) {
		localStorage.removeItem(SESSION_KEY)
		return
	}
	localStorage.setItem(SESSION_KEY, JSON.stringify({ id: user.id ?? null, username: user.username }))
}

export const signOut = () => {
	localStorage.removeItem(SESSION_KEY)
}

// Simulated sign-in: match username against real users, fall back to
// MOCK_USERS offline; any non-empty password is accepted client-side.
export const signIn = async ({ username, password }) => {
	const name = username.trim()
	if (!name || !password) throw new Error("Invalid username or password.")
	let users = null
	try {
		users = await userApi.getUsers()
	} catch {
		users = MOCK_USERS
	}
	const match = (users || []).find((u) => u.username.toLowerCase() === name.toLowerCase())
	if (!match) throw new Error("Invalid username or password.")
	const session = { id: match.id ?? null, username: match.username }
	setSessionUser(session)
	return session
}
