// Generated by Muse Spark on 2026-09-12
export const ApiStatusBadge = ({ status, checkedUrl, lastChecked, onRetry }) => {
	return (
		<div className={`api-status api-status-${status}`}>
			{status === "checking" ? (
				<output className="api-status-output">
					<span className="api-status-spinner" aria-hidden="true" />
					<span>Checking…</span>
				</output>
			) : (
				<output className="api-status-output">
					<span className="api-status-dot" aria-hidden="true" />
					<span>{status === "online" ? "Online" : "Offline — backend unreachable"}</span>
				</output>
			)}
			<p className="api-status-meta">
				<span>URL: {checkedUrl}</span>
				{lastChecked && <span>Last checked: {lastChecked.toLocaleTimeString()}</span>}
			</p>
			<button type="button" className="btn btn-secondary" onClick={onRetry} disabled={status === "checking"}>
				Retry
			</button>
		</div>
	)
}
