// Generated by Gemini 3.1 Pro on 2026-09-15
import { Lock } from "lucide-react"
import { Link } from "wouter"

const AuthRequiredPrompt = () => {
	return (
		<section className="auth-prompt-card" role="alert">
			<Lock className="auth-prompt-icon" />
			<h2>Authentication Required</h2>
			<p>Please sign in or create an account to view and manage tasks and projects.</p>
			<div className="auth-prompt-actions">
				<Link href="/register" className="btn btn-primary">
					Sign In / Register
				</Link>
			</div>
		</section>
	)
}

export default AuthRequiredPrompt
