// Generated by Gemini 3.1 Pro on 2026-09-15
import { render, screen } from "@testing-library/react"
import { describe, expect, it } from "vitest"
import { Router } from "wouter"
import { memoryLocation } from "wouter/memory-location"
import AuthRequiredPrompt from "./AuthRequiredPrompt"

describe("AuthRequiredPrompt", () => {
	it("renders an accessible prompt linking to /register", () => {
		const { hook } = memoryLocation({ path: "/" })
		render(
			<Router hook={hook}>
				<AuthRequiredPrompt />
			</Router>,
		)

		expect(screen.getByRole("alert")).toBeInTheDocument()
		expect(screen.getByText("Authentication Required")).toBeInTheDocument()

		const link = screen.getByRole("link", { name: /sign in \/ register/i })
		expect(link).toHaveAttribute("href", "/register")
	})
})
