// Generated by Muse Spark on 2026-09-12
import { render, screen, waitFor } from "@testing-library/react"
import userEvent from "@testing-library/user-event"
import { describe, expect, it, vi } from "vitest"
import { AuthForm } from "./AuthForm"

const renderForm = (props = {}) => render(<AuthForm mode="signin" onSubmit={vi.fn()} isSubmitting={false} {...props} />)

describe("AuthForm", () => {
	it("renders username and password fields without confirm in signin mode", () => {
		renderForm()

		expect(screen.getByLabelText("Username")).toBeInTheDocument()
		expect(screen.getByLabelText("Password")).toBeInTheDocument()
		expect(screen.queryByLabelText("Confirm password")).not.toBeInTheDocument()
		expect(screen.getByRole("button", { name: "Sign in" })).toBeInTheDocument()
	})

	it("renders the confirm field in signup mode", () => {
		renderForm({ mode: "signup" })

		expect(screen.getByLabelText("Confirm password")).toBeInTheDocument()
		expect(screen.getByRole("button", { name: "Sign up" })).toBeInTheDocument()
	})

	it("validates a short username before submitting", async () => {
		const user = userEvent.setup()
		const onSubmit = vi.fn()
		renderForm({ onSubmit })

		await user.type(screen.getByLabelText("Password"), "secret123")
		await user.click(screen.getByRole("button", { name: "Sign in" }))

		expect(await screen.findByRole("alert")).toHaveTextContent("Username must be at least 3 characters.")
		expect(onSubmit).not.toHaveBeenCalled()
	})

	it("validates short signup passwords and mismatched confirmation", async () => {
		const user = userEvent.setup()
		const onSubmit = vi.fn()
		renderForm({ mode: "signup", onSubmit })

		await user.type(screen.getByLabelText("Username"), "maya")
		await user.type(screen.getByLabelText("Password"), "short")
		await user.type(screen.getByLabelText("Confirm password"), "short")
		await user.click(screen.getByRole("button", { name: "Sign up" }))
		expect(await screen.findByRole("alert")).toHaveTextContent("at least 8 characters")
		expect(onSubmit).not.toHaveBeenCalled()

		await user.clear(screen.getByLabelText("Password"))
		await user.clear(screen.getByLabelText("Confirm password"))
		await user.type(screen.getByLabelText("Password"), "long-enough-password")
		await user.type(screen.getByLabelText("Confirm password"), "different-password")
		await user.click(screen.getByRole("button", { name: "Sign up" }))
		expect(await screen.findByRole("alert")).toHaveTextContent("Passwords do not match.")
		expect(onSubmit).not.toHaveBeenCalled()
	})

	it("submits trimmed credentials and toggles password visibility", async () => {
		const user = userEvent.setup()
		const onSubmit = vi.fn().mockResolvedValue(undefined)
		renderForm({ onSubmit })

		const passwordInput = screen.getByLabelText("Password")
		expect(passwordInput).toHaveAttribute("type", "password")
		await user.click(screen.getByRole("button", { name: "Show password" }))
		expect(passwordInput).toHaveAttribute("type", "text")

		await user.type(screen.getByLabelText("Username"), "  maya  ")
		await user.type(passwordInput, "secret")
		await user.click(screen.getByRole("button", { name: "Sign in" }))

		await waitFor(() => expect(onSubmit).toHaveBeenCalledWith({ username: "maya", password: "secret", confirmPassword: "" }))
	})

	it("disables inputs while submitting and surfaces server errors", () => {
		renderForm({ isSubmitting: true, serverError: "Invalid username or password." })

		expect(screen.getByLabelText("Username")).toBeDisabled()
		expect(screen.getByRole("button", { name: "Please wait…" })).toBeDisabled()
		expect(screen.getByRole("alert")).toHaveTextContent("Invalid username or password.")
	})
})
