// Generated by Muse Spark on 2026-09-12
import { Eye, EyeOff } from "lucide-react"
import { useState } from "react"

export const AuthForm = ({ mode, onSubmit, isSubmitting, serverError }) => {
	const isSignup = mode === "signup"
	const [username, setUsername] = useState("")
	const [password, setPassword] = useState("")
	const [confirmPassword, setConfirmPassword] = useState("")
	const [showPassword, setShowPassword] = useState(false)
	const [fieldError, setFieldError] = useState("")

	const handleSubmit = async (event) => {
		event.preventDefault()
		const name = username.trim()
		if (name.length < 3) {
			setFieldError("Username must be at least 3 characters.")
			return
		}
		const minPassword = isSignup ? 8 : 4
		if (password.length < minPassword) {
			setFieldError(`Password must be at least ${minPassword} characters.`)
			return
		}
		if (isSignup && password !== confirmPassword) {
			setFieldError("Passwords do not match.")
			return
		}
		setFieldError("")
		await onSubmit({ username: name, password, confirmPassword })
	}

	return (
		<form className="auth-form" onSubmit={handleSubmit} noValidate={false}>
			<div className="form-group">
				<label className="form-label" htmlFor="auth-username">
					Username
				</label>
				<input
					id="auth-username"
					type="text"
					className="form-input"
					autoComplete="username"
					value={username}
					onChange={(event) => setUsername(event.target.value)}
					disabled={isSubmitting}
				/>
			</div>
			<div className="form-group">
				<label className="form-label" htmlFor="auth-password">
					Password
				</label>
				<input
					id="auth-password"
					type={showPassword ? "text" : "password"}
					className="form-input"
					autoComplete={isSignup ? "new-password" : "current-password"}
					value={password}
					onChange={(event) => setPassword(event.target.value)}
					disabled={isSubmitting}
				/>
			</div>
			{isSignup && (
				<div className="form-group">
					<label className="form-label" htmlFor="auth-confirm-password">
						Confirm password
					</label>
					<input
						id="auth-confirm-password"
						type={showPassword ? "text" : "password"}
						className="form-input"
						autoComplete="new-password"
						value={confirmPassword}
						onChange={(event) => setConfirmPassword(event.target.value)}
						disabled={isSubmitting}
					/>
				</div>
			)}
			<button
				type="button"
				className="btn btn-secondary"
				onClick={() => setShowPassword((current) => !current)}
				aria-pressed={showPassword}
				disabled={isSubmitting}
			>
				{showPassword ? <EyeOff size={16} /> : <Eye size={16} />}
				<span>{showPassword ? "Hide password" : "Show password"}</span>
			</button>
			{(fieldError || serverError) && (
				<p className="auth-error" role="alert">
					{fieldError || serverError}
				</p>
			)}
			<button type="submit" className="btn btn-primary" disabled={isSubmitting}>
				<span>{isSubmitting ? "Please wait…" : isSignup ? "Sign up" : "Sign in"}</span>
			</button>
		</form>
	)
}
