// Generated by Muse Spark 1.2 on 2026-08-31
import { X } from "lucide-react"
import { useEffect, useRef } from "react"

export const ConfirmDialog = ({ isOpen, title, message, confirmLabel = "Delete", cancelLabel = "Cancel", variant = "danger", onConfirm, onCancel }) => {
	const cancelRef = useRef(null)
	const confirmRef = useRef(null)

	useEffect(() => {
		if (!isOpen) return
		const id = requestAnimationFrame(() => cancelRef.current?.focus())

		const handleKeyDown = (event) => {
			if (event.key === "Escape") {
				event.stopPropagation()
				onCancel()
			}
			if (event.key === "Tab") {
				const focusable = [cancelRef.current, confirmRef.current].filter(Boolean)
				if (focusable.length === 0) return
				const first = focusable[0]
				const last = focusable[focusable.length - 1]
				if (event.shiftKey && document.activeElement === first) {
					event.preventDefault()
					last.focus()
				} else if (!event.shiftKey && document.activeElement === last) {
					event.preventDefault()
					first.focus()
				}
			}
		}

		document.addEventListener("keydown", handleKeyDown)
		return () => {
			cancelAnimationFrame(id)
			document.removeEventListener("keydown", handleKeyDown)
		}
	}, [isOpen, onCancel])

	if (!isOpen) return null

	return (
		<div className="confirm-overlay" onClick={onCancel} onKeyDown={(event) => event.key === "Escape" && onCancel()}>
			<div
				className="confirm-dialog"
				// biome-ignore lint/a11y/useSemanticElements: dialog requires div for overlay styling
				role="dialog"
				aria-modal="true"
				aria-labelledby="confirm-dialog-title"
				onClick={(event) => event.stopPropagation()}
				onKeyDown={(event) => event.stopPropagation()}
			>
				<div className="confirm-header">
					<h3 id="confirm-dialog-title" className="confirm-title">
						{title}
					</h3>
					<button type="button" className="btn btn-icon" onClick={onCancel} aria-label="Close confirmation dialog">
						<X size={16} />
					</button>
				</div>
				<div className="confirm-body">
					<p className="confirm-message">{message}</p>
				</div>
				<div className="confirm-footer">
					<button type="button" ref={cancelRef} className="btn btn-secondary" onClick={onCancel}>
						{cancelLabel}
					</button>
					<button
						type="button"
						ref={confirmRef}
						className={variant === "danger" ? "btn btn-primary confirm-btn-danger" : "btn btn-primary"}
						onClick={onConfirm}
						onKeyDown={(event) => {
							if (event.key === "Enter") onConfirm()
						}}
					>
						{confirmLabel}
					</button>
				</div>
			</div>
		</div>
	)
}
