// Generated by Gemini 3.6 Flash on 2026-09-06
import { render, screen, waitFor } from "@testing-library/react"
import userEvent from "@testing-library/user-event"
import { describe, expect, it, vi } from "vitest"
import { CreateProjectForm } from "./CreateProjectForm"

describe("CreateProjectForm", () => {
	it("keeps submission unavailable for whitespace-only names", async () => {
		const user = userEvent.setup()
		render(<CreateProjectForm onCreate={vi.fn()} />)

		const input = screen.getByLabelText("Project name")
		await user.type(input, "   ")

		expect(screen.getByRole("button", { name: "Add project" })).toBeDisabled()
	})

	it("submits a trimmed name and clears the field after success", async () => {
		const user = userEvent.setup()
		const onCreate = vi.fn().mockResolvedValue({ id: 12, name: "Website refresh" })
		render(<CreateProjectForm onCreate={onCreate} />)

		const input = screen.getByLabelText("Project name")
		await user.type(input, "  Website refresh  ")
		await user.click(screen.getByRole("button", { name: "Add project" }))

		await waitFor(() => expect(onCreate).toHaveBeenCalledWith("Website refresh"))
		expect(input).toHaveValue("")
	})

	it("prevents duplicate submissions while a creation is pending", async () => {
		const user = userEvent.setup()
		let resolveCreate
		const onCreate = vi.fn(
			() =>
				new Promise((resolve) => {
					resolveCreate = resolve
				}),
		)
		render(<CreateProjectForm onCreate={onCreate} />)

		await user.type(screen.getByLabelText("Project name"), "Mobile app")
		const submitButton = screen.getByRole("button", { name: "Add project" })
		await user.click(submitButton)
		await user.click(submitButton)

		expect(onCreate).toHaveBeenCalledTimes(1)
		expect(submitButton).toBeDisabled()

		resolveCreate({ id: 13, name: "Mobile app" })
		await waitFor(() => expect(screen.getByLabelText("Project name")).toHaveValue(""))
	})
})
