// Generated by Claude Opus 4.6 on 2026-08-29
import { Plus } from "lucide-react"
import { useState } from "react"

export const CreateProjectForm = ({ onCreate, inputId = "create-project-name" }) => {
	const [projectName, setProjectName] = useState("")
	const [isSubmitting, setIsSubmitting] = useState(false)

	const handleSubmit = async (event) => {
		event.preventDefault()
		const name = projectName.trim()
		if (!name) return
		setIsSubmitting(true)
		try {
			const created = await onCreate(name)
			if (created) setProjectName("")
		} finally {
			setIsSubmitting(false)
		}
	}

	return (
		<form className="project-create-form" onSubmit={handleSubmit}>
			<label className="sr-only" htmlFor={inputId}>
				Project name
			</label>
			<input
				id={inputId}
				type="text"
				className="form-input"
				placeholder="New project name"
				value={projectName}
				onChange={(event) => setProjectName(event.target.value)}
				disabled={isSubmitting}
			/>
			<button type="submit" className="btn btn-primary" disabled={isSubmitting || !projectName.trim()}>
				<Plus size={16} />
				<span>{isSubmitting ? "Adding…" : "Add project"}</span>
			</button>
		</form>
	)
}
