// Generated by Claude Opus 4.6 on 2026-08-29
import { Plus } from "lucide-react"
import { useState } from "react"

export const CreateProjectForm = ({ onCreate }) => {
	const [projectName, setProjectName] = useState("")

	const handleSubmit = async (event) => {
		event.preventDefault()
		const name = projectName.trim()
		if (!name) return
		const created = await onCreate(name)
		if (created) setProjectName("")
	}

	return (
		<form className="project-create-form" onSubmit={handleSubmit}>
			<label className="sr-only" htmlFor="create-project-name">
				Project name
			</label>
			<input
				id="create-project-name"
				type="text"
				className="form-input"
				placeholder="New project name"
				value={projectName}
				onChange={(event) => setProjectName(event.target.value)}
			/>
			<button type="submit" className="btn btn-primary" disabled={!projectName.trim()}>
				<Plus size={16} />
				<span>Add project</span>
			</button>
		</form>
	)
}
