// Generated by Gemini 3.1 Pro on 2026-09-15
import { render, screen, waitFor } from "@testing-library/react"
import { beforeEach, describe, expect, it, vi } from "vitest"
import { Router } from "wouter"
import { memoryLocation } from "wouter/memory-location"
import { OfflineQueueProvider } from "../context/OfflineQueueContext"
import { taskApi } from "../services/api"
import { KanbanBoard } from "./KanbanBoard"

vi.mock("../services/api", () => ({
	taskApi: {
		getTasks: vi.fn(),
	},
}))

describe("KanbanBoard Authentication Handling", () => {
	beforeEach(() => {
		vi.resetAllMocks()
	})

	it("displays AuthRequiredPrompt on 401 error", async () => {
		taskApi.getTasks.mockRejectedValue({ status: 401, name: "ApiError" })

		const { hook } = memoryLocation({ path: "/" })
		render(
			<Router hook={hook}>
				<OfflineQueueProvider>
					<KanbanBoard projects={[]} enabledProjectIds={[]} />
				</OfflineQueueProvider>
			</Router>,
		)

		await waitFor(() => {
			expect(screen.getByRole("alert")).toBeInTheDocument()
		})
		expect(screen.getByText("Authentication Required")).toBeInTheDocument()

		const link = screen.getByRole("link", { name: /sign in \/ register/i })
		expect(link).toHaveAttribute("href", "/register")
	})

	it("displays AuthRequiredPrompt on 403 error", async () => {
		taskApi.getTasks.mockRejectedValue({ status: 403, name: "ApiError" })

		const { hook } = memoryLocation({ path: "/" })
		render(
			<Router hook={hook}>
				<OfflineQueueProvider>
					<KanbanBoard projects={[]} enabledProjectIds={[]} />
				</OfflineQueueProvider>
			</Router>,
		)

		await waitFor(() => {
			expect(screen.getByRole("alert")).toBeInTheDocument()
		})
		expect(screen.getByText("Authentication Required")).toBeInTheDocument()
	})
})
