// Generated by Gemini 3.6 Flash on 2026-08-19
import { useCallback, useEffect, useState } from "react"
import { projectApi, taskApi } from "../services/api"
import { KanbanColumn } from "./KanbanColumn"
import { ProjectManager } from "./ProjectManager"

const COLUMNS = [
	{ id: "TODO", title: "To Do", color: "var(--status-todo)" },
	{ id: "IN_PROGRESS", title: "In Progress", color: "var(--status-in_progress)" },
	{ id: "REVIEW", title: "Review", color: "var(--status-review)" },
	{ id: "DONE", title: "Done", color: "var(--status-done)" },
]

const INITIAL_LOCAL_TASKS = [
	{
		id: 1,
		title: "Design Kanban Board Layout",
		description: "Implement drag and drop columns with theme tokens and glassmorphic card styling.",
		status: "DONE",
		priority: "HIGH",
		assignee: "Admin",
	},
	{
		id: 2,
		title: "Implement Django REST Framework API",
		description: "Configure Task model, serializers, viewsets, and CORS middleware.",
		status: "IN_PROGRESS",
		priority: "HIGH",
		assignee: "Admin",
	},
	{
		id: 3,
		title: "Native Drag and Drop Handler",
		description: "Build native HTML5 drag and drop events (onDragStart, onDragOver, onDrop).",
		status: "IN_PROGRESS",
		priority: "MEDIUM",
		assignee: "Admin",
	},
	{
		id: 4,
		title: "Light and Dark Mode Toggle",
		description: "Persistent theme toggle with prefers-color-scheme detection and CSS variables.",
		status: "TODO",
		priority: "LOW",
		assignee: "Admin",
	},
]

const withProjectDetails = (task, projectIds, projects) => ({
	...task,
	project_ids: projectIds,
	projects: projectIds.map((projectId) => projects.find((project) => project.id === projectId)).filter(Boolean),
})

export const KanbanBoard = ({ onOpenModalWithTask, registerSaveHandler, isProjectManagerOpen }) => {
	const [tasks, setTasks] = useState([])
	const [loading, setLoading] = useState(true)
	const [useFallback, setUseFallback] = useState(false)
	const [projects, setProjects] = useState([])
	const [enabledProjectIds, setEnabledProjectIds] = useState([])
	const [projectsLoading, setProjectsLoading] = useState(true)
	const [projectsError, setProjectsError] = useState("")

	const fetchTasks = useCallback(async () => {
		try {
			setLoading(true)
			const data = await taskApi.getTasks()
			setTasks(data)
			setUseFallback(false)
		} catch (err) {
			console.info("Using local state fallback while backend server connects...")
			setTasks(INITIAL_LOCAL_TASKS)
			setUseFallback(true)
		} finally {
			setLoading(false)
		}
	}, [])

	useEffect(() => {
		fetchTasks()
	}, [fetchTasks])

	const fetchProjects = useCallback(async () => {
		try {
			setProjectsLoading(true)
			setProjectsError("")
			setProjects(await projectApi.getProjects())
		} catch {
			setProjectsError("Projects could not be loaded.")
		} finally {
			setProjectsLoading(false)
		}
	}, [])

	useEffect(() => {
		fetchProjects()
	}, [fetchProjects])

	const visibleTasks =
		enabledProjectIds.length === 0
			? tasks
			: tasks.filter((task) => (task.project_ids || task.projects?.map((project) => project.id) || []).some((id) => enabledProjectIds.includes(id)))

	const handleToggleProject = (projectId) => {
		setEnabledProjectIds((current) => (current.includes(projectId) ? current.filter((id) => id !== projectId) : [...current, projectId]))
	}

	const handleCreateProject = async (name) => {
		try {
			const project = await projectApi.createProject(name)
			setProjects((current) => [...current, project])
			return project
		} catch {
			setProjectsError("Project could not be created.")
			return null
		}
	}

	const handleDeleteProject = async (projectId) => {
		if (!window.confirm("Delete this project? Tasks will be preserved.")) return
		try {
			await projectApi.deleteProject(projectId)
			setProjects((current) => current.filter((project) => project.id !== projectId))
			setEnabledProjectIds((current) => current.filter((id) => id !== projectId))
			setTasks((current) =>
				current.map((task) => ({
					...task,
					project_ids: (task.project_ids || []).filter((id) => id !== projectId),
					projects: (task.projects || []).filter((project) => project.id !== projectId),
				})),
			)
		} catch {
			setProjectsError("Project could not be deleted.")
		}
	}

	const handleStatusChange = async (taskId, newStatus) => {
		setTasks((current) => current.map((task) => (task.id === taskId ? { ...task, status: newStatus } : task)))

		if (!useFallback) {
			try {
				await taskApi.updateTask(taskId, { status: newStatus })
			} catch (err) {
				console.error("Failed to sync status update with backend:", err)
			}
		}
	}

	const handleDropTask = async (taskId, targetStatus, targetTaskId) => {
		const targetTask = tasks.find((t) => t.id === taskId)
		if (!targetTask) return

		// Optimistic update locally
		setTasks((current) => {
			const updated = current.filter((t) => t.id !== taskId)
			const movedTask = { ...targetTask, status: targetStatus }

			if (targetTaskId) {
				const targetIdx = updated.findIndex((t) => t.id === targetTaskId)
				if (targetIdx !== -1) {
					// Insert at targetIdx to push target and subsequent tasks down
					updated.splice(targetIdx, 0, movedTask)
				} else {
					updated.push(movedTask)
				}
			} else {
				// Insert at end of the status group
				updated.push(movedTask)
			}
			return updated
		})

		if (!useFallback) {
			try {
				await taskApi.reorderTask(taskId, targetStatus, targetTaskId)
				fetchTasks() // Sync positions accurately from backend
			} catch (err) {
				console.error("Failed to sync drop reorder with backend:", err)
				fetchTasks() // Revert on failure
			}
		}
	}

	const handleDeleteTask = async (taskId) => {
		if (!window.confirm("Are you sure you want to delete this task?")) return
		setTasks(tasks.filter((t) => t.id !== taskId))

		if (!useFallback) {
			try {
				await taskApi.deleteTask(taskId)
			} catch (err) {
				console.error("Failed to delete task on backend:", err)
			}
		}
	}

	const handleSaveTask = useCallback(
		async (formData) => {
			const existingTask = tasks.find((t) => t.title === formData.title && t.id)
			if (existingTask) {
				const updatedTasks = tasks.map((task) =>
					task.id === existingTask.id ? withProjectDetails({ ...task, ...formData }, formData.project_ids, projects) : task,
				)
				setTasks(updatedTasks)

				if (!useFallback) {
					try {
						const updatedTask = await taskApi.updateTask(existingTask.id, formData)
						setTasks((current) =>
							current.map((task) =>
								task.id === existingTask.id ? withProjectDetails(updatedTask, updatedTask.project_ids || [], projects) : task,
							),
						)
					} catch (err) {
						console.error("Failed to update task:", err)
					}
				}
			} else {
				const tempId = Date.now()
				const newTask = { id: tempId, ...formData }
				setTasks([newTask, ...tasks])

				if (!useFallback) {
					try {
						const created = await taskApi.createTask(formData)
						setTasks((prev) => prev.map((t) => (t.id === tempId ? created : t)))
					} catch (err) {
						console.error("Failed to create task on backend:", err)
					}
				}
			}
		},
		[tasks, projects, useFallback],
	)

	useEffect(() => {
		if (registerSaveHandler) {
			registerSaveHandler(handleSaveTask)
		}
	}, [registerSaveHandler, handleSaveTask])

	if (loading) {
		return <div className="loading-spinner">Loading Kanban Board...</div>
	}

	return (
		<div className="main-container">
			<div className={`project-panel-shell${isProjectManagerOpen ? " is-open" : ""}`} aria-hidden={!isProjectManagerOpen}>
				<ProjectManager
					projects={projects}
					enabledProjectIds={enabledProjectIds}
					loading={projectsLoading}
					error={projectsError}
					onRetry={fetchProjects}
					onToggle={handleToggleProject}
					onCreate={handleCreateProject}
					onDelete={handleDeleteProject}
				/>
			</div>
			<div className="board-stats">
				<div className="stat-pill">
					<span>Total Tasks:</span>
					<span className="stat-count">{visibleTasks.length}</span>
				</div>
				<div className="stat-pill">
					<span>To Do:</span>
					<span className="stat-count">{visibleTasks.filter((t) => t.status === "TODO").length}</span>
				</div>
				<div className="stat-pill">
					<span>In Progress:</span>
					<span className="stat-count">{visibleTasks.filter((t) => t.status === "IN_PROGRESS").length}</span>
				</div>
				<div className="stat-pill">
					<span>Completed:</span>
					<span className="stat-count">{visibleTasks.filter((t) => t.status === "DONE").length}</span>
				</div>
			</div>

			<div className="kanban-grid">
				{COLUMNS.map((column) => (
					<KanbanColumn
						key={column.id}
						column={column}
						tasks={visibleTasks.filter((t) => t.status === column.id)}
						onEditTask={onOpenModalWithTask}
						onDeleteTask={handleDeleteTask}
						onStatusChange={handleStatusChange}
						onDropTask={handleDropTask}
					/>
				))}
			</div>
		</div>
	)
}
