// Generated by Gemini 3.6 Flash on 2026-08-19
import React, { useState, useEffect } from 'react'
import { KanbanColumn } from './KanbanColumn'
import { taskApi } from '../services/api'

const COLUMNS = [
	{ id: 'TODO', title: 'To Do', color: 'var(--status-todo)' },
	{ id: 'IN_PROGRESS', title: 'In Progress', color: 'var(--status-in_progress)' },
	{ id: 'REVIEW', title: 'Review', color: 'var(--status-review)' },
	{ id: 'DONE', title: 'Done', color: 'var(--status-done)' },
]

const INITIAL_LOCAL_TASKS = [
	{
		id: 1,
		title: 'Design Kanban Board Layout',
		description: 'Implement drag and drop columns with theme tokens and glassmorphic card styling.',
		status: 'DONE',
		priority: 'HIGH',
		assignee: 'Admin',
	},
	{
		id: 2,
		title: 'Implement Django REST Framework API',
		description: 'Configure Task model, serializers, viewsets, and CORS middleware.',
		status: 'IN_PROGRESS',
		priority: 'HIGH',
		assignee: 'Admin',
	},
	{
		id: 3,
		title: 'Native Drag and Drop Handler',
		description: 'Build native HTML5 drag and drop events (onDragStart, onDragOver, onDrop).',
		status: 'IN_PROGRESS',
		priority: 'MEDIUM',
		assignee: 'Admin',
	},
	{
		id: 4,
		title: 'Light and Dark Mode Toggle',
		description: 'Persistent theme toggle with prefers-color-scheme detection and CSS variables.',
		status: 'TODO',
		priority: 'LOW',
		assignee: 'Admin',
	},
]

export const KanbanBoard = ({ onOpenModalWithTask, registerSaveHandler }) => {
	const [tasks, setTasks] = useState([])
	const [loading, setLoading] = useState(true)
	const [useFallback, setUseFallback] = useState(false)

	const fetchTasks = async () => {
		try {
			setLoading(true)
			const data = await taskApi.getTasks()
			setTasks(data)
			setUseFallback(false)
		} catch (err) {
			console.info('Using local state fallback while backend server connects...')
			setTasks(INITIAL_LOCAL_TASKS)
			setUseFallback(true)
		} finally {
			setLoading(false)
		}
	}

	useEffect(() => {
		fetchTasks()
	}, [])

	const handleStatusChange = async (taskId, newStatus) => {
		const updatedTasks = tasks.map((t) => (t.id === taskId ? { ...t, status: newStatus } : t))
		setTasks(updatedTasks)

		if (!useFallback) {
			try {
				await taskApi.updateTask(taskId, { status: newStatus })
			} catch (err) {
				console.error('Failed to sync status update with backend:', err)
			}
		}
	}

	const handleDropTask = (taskId, targetStatus) => {
		const targetTask = tasks.find((t) => t.id === taskId)
		if (targetTask && targetTask.status !== targetStatus) {
			handleStatusChange(taskId, targetStatus)
		}
	}

	const handleDeleteTask = async (taskId) => {
		if (!window.confirm('Are you sure you want to delete this task?')) return
		setTasks(tasks.filter((t) => t.id !== taskId))

		if (!useFallback) {
			try {
				await taskApi.deleteTask(taskId)
			} catch (err) {
				console.error('Failed to delete task on backend:', err)
			}
		}
	}

	const handleSaveTask = async (formData) => {
		const existingTask = tasks.find((t) => t.title === formData.title && t.id)
		if (existingTask) {
			const updatedTasks = tasks.map((t) => (t.id === existingTask.id ? { ...t, ...formData } : t))
			setTasks(updatedTasks)

			if (!useFallback) {
				try {
					await taskApi.updateTask(existingTask.id, formData)
				} catch (err) {
					console.error('Failed to update task:', err)
				}
			}
		} else {
			const tempId = Date.now()
			const newTask = { id: tempId, ...formData }
			setTasks([newTask, ...tasks])

			if (!useFallback) {
				try {
					const created = await taskApi.createTask(formData)
					setTasks((prev) => prev.map((t) => (t.id === tempId ? created : t)))
				} catch (err) {
					console.error('Failed to create task on backend:', err)
				}
			}
		}
	}

	useEffect(() => {
		if (registerSaveHandler) {
			registerSaveHandler(handleSaveTask)
		}
	}, [tasks, useFallback, registerSaveHandler])

	if (loading) {
		return <div className="loading-spinner">Loading Kanban Board...</div>
	}

	return (
		<div className="main-container">
			<div className="board-stats">
				<div className="stat-pill">
					<span>Total Tasks:</span>
					<span className="stat-count">{tasks.length}</span>
				</div>
				<div className="stat-pill">
					<span>To Do:</span>
					<span className="stat-count">{tasks.filter((t) => t.status === 'TODO').length}</span>
				</div>
				<div className="stat-pill">
					<span>In Progress:</span>
					<span className="stat-count">{tasks.filter((t) => t.status === 'IN_PROGRESS').length}</span>
				</div>
				<div className="stat-pill">
					<span>Completed:</span>
					<span className="stat-count">{tasks.filter((t) => t.status === 'DONE').length}</span>
				</div>
			</div>

			<div className="kanban-grid">
				{COLUMNS.map((column) => (
					<KanbanColumn
						key={column.id}
						column={column}
						tasks={tasks.filter((t) => t.status === column.id)}
						onEditTask={onOpenModalWithTask}
						onDeleteTask={handleDeleteTask}
						onStatusChange={handleStatusChange}
						onDropTask={handleDropTask}
					/>
				))}
			</div>
		</div>
	)
}
