// Generated by Claude Opus 4.6 on 2026-09-04
import { useCallback, useEffect, useRef, useState } from "react"
import { useOfflineQueueContext } from "../context/OfflineQueueContext"
import { taskApi } from "../services/api"
import { API_BASE_URL } from "../utils/apiClient"
import { COLUMNS } from "../utils/constants"
import { isNetworkError } from "../utils/offlineQueue"
import { getVisibleTasks, withProjectDetails } from "../utils/taskHelpers"
import { ConfirmDialog } from "./ConfirmDialog"
import { KanbanColumn } from "./KanbanColumn"
import { SyncIndicator } from "./SyncIndicator"

export const KanbanBoard = ({ onOpenModalWithTask, registerSaveHandler, projects, enabledProjectIds, projectsLoading }) => {
	const [tasks, setTasks] = useState([])
	const [initialLoading, setInitialLoading] = useState(true)
	const [syncState, setSyncState] = useState({ status: "idle", message: "" })
	const [useFallback, setUseFallback] = useState(false)
	const [confirmDeleteId, setConfirmDeleteId] = useState(null)
	const { enqueue } = useOfflineQueueContext()
	const savedTimerRef = useRef(null)
	const syncVersionRef = useRef(0)

	const clearSavedTimer = useCallback(() => {
		if (savedTimerRef.current) {
			clearTimeout(savedTimerRef.current)
			savedTimerRef.current = null
		}
	}, [])

	const updateSyncState = useCallback(
		(nextState) => {
			clearSavedTimer()
			setSyncState(nextState)
		},
		[clearSavedTimer],
	)

	const showSaved = useCallback(
		(message = "Changes saved") => {
			clearSavedTimer()
			setSyncState({ status: "saved", message })
			savedTimerRef.current = setTimeout(() => {
				setSyncState({ status: "idle", message: "" })
				savedTimerRef.current = null
			}, 2500)
		},
		[clearSavedTimer],
	)

	const fetchTasks = useCallback(async ({ silent = false } = {}) => {
		if (!silent) setInitialLoading(true)
		try {
			const data = await taskApi.getTasks()
			setTasks(data)
			setUseFallback(false)
		} catch (err) {
			if (!silent) {
				console.info("Using local state fallback while backend server connects...")
				setTasks([])
				setUseFallback(true)
			}
		} finally {
			if (!silent) setInitialLoading(false)
		}
	}, [])

	useEffect(() => {
		fetchTasks()
	}, [fetchTasks])

	useEffect(() => {
		return () => {
			clearSavedTimer()
		}
	}, [clearSavedTimer])

	const visibleTasks = getVisibleTasks(tasks, enabledProjectIds)

	const handleStatusChange = async (taskId, newStatus) => {
		setTasks((current) => current.map((task) => (task.id === taskId ? { ...task, status: newStatus } : task)))

		if (!useFallback) {
			const syncId = ++syncVersionRef.current
			updateSyncState({ status: "syncing", message: "Updating status..." })
			try {
				await taskApi.updateTask(taskId, { status: newStatus })
				if (syncId === syncVersionRef.current) {
					showSaved("Status updated")
				}
			} catch (err) {
				console.error("Failed to sync status update with backend:", err)
				if (syncId === syncVersionRef.current) {
					if (enqueue && (!navigator.onLine || isNetworkError(err))) {
						enqueue({
							method: "PATCH",
							url: `${API_BASE_URL}/tasks/${taskId}/`,
							body: { status: newStatus },
							meta: { entity: "task", action: "update", originalTaskId: taskId },
						})
						updateSyncState({ status: "offline", message: "Saved offline" })
					} else {
						updateSyncState({ status: "idle", message: "" })
					}
				}
			}
		}
	}

	const handleDropTask = async (taskId, targetStatus, targetTaskId) => {
		const targetTask = tasks.find((t) => t.id === taskId)
		if (!targetTask) return

		setTasks((current) => {
			const updated = current.filter((t) => t.id !== taskId)
			const movedTask = { ...targetTask, status: targetStatus }

			if (targetTaskId) {
				const targetIdx = updated.findIndex((t) => t.id === targetTaskId)
				if (targetIdx !== -1) {
					updated.splice(targetIdx, 0, movedTask)
				} else {
					updated.push(movedTask)
				}
			} else {
				updated.push(movedTask)
			}
			return updated
		})

		if (!useFallback) {
			const syncId = ++syncVersionRef.current
			updateSyncState({ status: "syncing", message: "Updating card order..." })
			try {
				await taskApi.reorderTask(taskId, targetStatus, targetTaskId)
				await fetchTasks({ silent: true })
				if (syncId === syncVersionRef.current) {
					showSaved("Order saved")
				}
			} catch (err) {
				console.error("Failed to sync drop reorder with backend:", err)
				if (syncId === syncVersionRef.current) {
					if (enqueue && (!navigator.onLine || isNetworkError(err))) {
						enqueue({
							method: "POST",
							url: `${API_BASE_URL}/tasks/${taskId}/reorder/`,
							body: { status: targetStatus, target_task_id: targetTaskId },
							meta: { entity: "task", action: "reorder", originalTaskId: taskId },
						})
						updateSyncState({ status: "offline", message: "Saved offline" })
					} else {
						await fetchTasks({ silent: true })
						updateSyncState({ status: "idle", message: "" })
					}
				}
			}
		}
	}

	const handleDeleteTask = (taskId) => {
		setConfirmDeleteId(taskId)
	}

	const handleConfirmDelete = async () => {
		const id = confirmDeleteId
		setConfirmDeleteId(null)
		setTasks((current) => current.filter((t) => t.id !== id))

		if (!useFallback) {
			const syncId = ++syncVersionRef.current
			updateSyncState({ status: "syncing", message: "Deleting task..." })
			try {
				await taskApi.deleteTask(id)
				if (syncId === syncVersionRef.current) {
					showSaved("Task deleted")
				}
			} catch (err) {
				console.error("Failed to delete task on backend:", err)
				if (syncId === syncVersionRef.current) {
					if (enqueue && (!navigator.onLine || isNetworkError(err))) {
						enqueue({
							method: "DELETE",
							url: `${API_BASE_URL}/tasks/${id}/`,
							body: null,
							meta: { entity: "task", action: "delete", originalTaskId: id },
						})
						updateSyncState({ status: "offline", message: "Saved offline" })
					} else {
						updateSyncState({ status: "idle", message: "" })
					}
				}
			}
		}
	}

	const handleCancelDelete = () => setConfirmDeleteId(null)

	const handleSaveTask = useCallback(
		async (formData) => {
			const existingTask = tasks.find((t) => t.title === formData.title && t.id)
			if (existingTask) {
				const updatedTasks = tasks.map((task) =>
					task.id === existingTask.id ? withProjectDetails({ ...task, ...formData }, formData.project_ids, projects) : task,
				)
				setTasks(updatedTasks)

				if (!useFallback) {
					const syncId = ++syncVersionRef.current
					updateSyncState({ status: "syncing", message: "Saving changes..." })
					try {
						const updatedTask = await taskApi.updateTask(existingTask.id, formData)
						setTasks((current) =>
							current.map((task) =>
								task.id === existingTask.id ? withProjectDetails(updatedTask, updatedTask.project_ids || [], projects) : task,
							),
						)
						if (syncId === syncVersionRef.current) {
							showSaved("Changes saved")
						}
					} catch (err) {
						console.error("Failed to update task:", err)
						if (syncId === syncVersionRef.current) {
							if (enqueue && (!navigator.onLine || isNetworkError(err))) {
								enqueue({
									method: "PATCH",
									url: `${API_BASE_URL}/tasks/${existingTask.id}/`,
									body: formData,
									meta: { entity: "task", action: "update", originalTaskId: existingTask.id },
								})
								updateSyncState({ status: "offline", message: "Saved offline" })
							} else {
								updateSyncState({ status: "idle", message: "" })
							}
						}
					}
				}
			} else {
				const tempId = Date.now()
				const newTask = { id: tempId, ...formData }
				setTasks([newTask, ...tasks])

				if (!useFallback) {
					const syncId = ++syncVersionRef.current
					updateSyncState({ status: "syncing", message: "Creating task..." })
					try {
						const created = await taskApi.createTask(formData)
						setTasks((prev) => prev.map((t) => (t.id === tempId ? created : t)))
						if (syncId === syncVersionRef.current) {
							showSaved("Task created")
						}
					} catch (err) {
						console.error("Failed to create task on backend:", err)
						if (syncId === syncVersionRef.current) {
							if (enqueue && (!navigator.onLine || isNetworkError(err))) {
								enqueue({
									method: "POST",
									url: `${API_BASE_URL}/tasks/`,
									body: formData,
									meta: { entity: "task", action: "create", clientId: tempId },
								})
								updateSyncState({ status: "offline", message: "Saved offline" })
							} else {
								updateSyncState({ status: "idle", message: "" })
							}
						}
					}
				}
			}
		},
		[tasks, projects, useFallback, enqueue, showSaved, updateSyncState],
	)

	useEffect(() => {
		if (registerSaveHandler) {
			registerSaveHandler(handleSaveTask)
		}
	}, [registerSaveHandler, handleSaveTask])

	if (initialLoading) {
		return <div className="loading-spinner">Loading Kanban Board...</div>
	}

	return (
		<div className="main-container">
			<div className="board-stats">
				<div className="stat-pill">
					<span>Total Tasks:</span>
					<span className="stat-count">{visibleTasks.length}</span>
				</div>
				<div className="stat-pill">
					<span>To Do:</span>
					<span className="stat-count">{visibleTasks.filter((t) => t.status === "TODO").length}</span>
				</div>
				<div className="stat-pill">
					<span>In Progress:</span>
					<span className="stat-count">{visibleTasks.filter((t) => t.status === "IN_PROGRESS").length}</span>
				</div>
				<div className="stat-pill">
					<span>Completed:</span>
					<span className="stat-count">{visibleTasks.filter((t) => t.status === "DONE").length}</span>
				</div>
				<SyncIndicator status={syncState.status} message={syncState.message} />
			</div>

			<div className="kanban-grid">
				{COLUMNS.map((column) => (
					<KanbanColumn
						key={column.id}
						column={column}
						tasks={visibleTasks.filter((t) => t.status === column.id)}
						onEditTask={onOpenModalWithTask}
						onDeleteTask={handleDeleteTask}
						onStatusChange={handleStatusChange}
						onDropTask={handleDropTask}
					/>
				))}
			</div>
			<ConfirmDialog
				isOpen={confirmDeleteId !== null}
				title="Delete task?"
				message="Are you sure you want to delete this task? This cannot be undone."
				confirmLabel="Delete"
				cancelLabel="Cancel"
				variant="danger"
				onConfirm={handleConfirmDelete}
				onCancel={handleCancelDelete}
			/>
		</div>
	)
}
