// Generated by Gemini 3.6 Flash on 2026-08-19
import { useState } from 'react'
import { TaskCard } from './TaskCard'

export const KanbanColumn = ({ column, tasks, onEditTask, onDeleteTask, onStatusChange, onDropTask }) => {
	const [isDragOver, setIsDragOver] = useState(false)

	const handleDragOver = (e) => {
		e.preventDefault()
		e.dataTransfer.dropEffect = 'move'
		if (!isDragOver) setIsDragOver(true)
	}

	const handleDragLeave = (e) => {
		e.preventDefault()
		setIsDragOver(false)
	}

	const handleDrop = (e) => {
		e.preventDefault()
		setIsDragOver(false)
		const taskIdStr = e.dataTransfer.getData('text/plain')
		const taskId = Number.parseInt(taskIdStr, 10)
		if (taskId) {
			onDropTask(taskId, column.id)
		}
	}

	return (
		<div className={`kanban-column ${isDragOver ? 'drag-over' : ''}`} onDragOver={handleDragOver} onDragLeave={handleDragLeave} onDrop={handleDrop}>
			<div className="column-header">
				<div className="column-title-group">
					<span className="column-dot" style={{ backgroundColor: column.color }} />
					<h3 className="column-title">{column.title}</h3>
				</div>
				<span className="column-count">{tasks.length}</span>
			</div>

			<div className="task-list">
				{tasks.length === 0 ? (
					<div className="empty-column">
						<span>No tasks in {column.title}</span>
					</div>
				) : (
					tasks.map((task) => <TaskCard key={task.id} task={task} onEdit={onEditTask} onDelete={onDeleteTask} onStatusChange={onStatusChange} />)
				)}
			</div>
		</div>
	)
}
