// Generated by Gemini 3.6 Flash on 2026-08-29
import { ChevronDown, X } from "lucide-react"
import { useEffect, useRef, useState } from "react"

export const MultiSelect = ({ options, selectedIds, onChange, placeholder = "Select items..." }) => {
	const [isOpen, setIsOpen] = useState(false)
	const containerRef = useRef(null)

	const selectedItems = options.filter((opt) => selectedIds.includes(opt.id))

	const handleToggle = (id) => {
		const newIds = selectedIds.includes(id) ? selectedIds.filter((selectedId) => selectedId !== id) : [...selectedIds, id]
		onChange(newIds)
	}

	const handleRemove = (id, e) => {
		e.stopPropagation()
		onChange(selectedIds.filter((selectedId) => selectedId !== id))
	}

	const handleClearAll = (e) => {
		e.stopPropagation()
		onChange([])
	}

	useEffect(() => {
		const handleClickOutside = (e) => {
			if (containerRef.current && !containerRef.current.contains(e.target)) {
				setIsOpen(false)
			}
		}

		if (isOpen) {
			document.addEventListener("mousedown", handleClickOutside)
			return () => {
				document.removeEventListener("mousedown", handleClickOutside)
			}
		}
	}, [isOpen])

	return (
		<div className="multi-select-container" ref={containerRef}>
			<button
				type="button"
				className={`multi-select-trigger${isOpen ? " open" : ""}`}
				onClick={() => setIsOpen(!isOpen)}
				aria-haspopup="listbox"
				aria-expanded={isOpen}
				aria-label="Select projects"
			>
				<div className="multi-select-value">
					{selectedItems.length > 0 ? (
						<div className="multi-select-tags">
							{selectedItems.map((item) => (
								<div className="multi-select-tag" key={item.id}>
									<span>{item.name}</span>
									<button
										type="button"
										className="multi-select-tag-remove"
										onClick={(e) => handleRemove(item.id, e)}
										title={`Remove ${item.name}`}
										aria-label={`Remove ${item.name}`}
									>
										<X size={14} />
									</button>
								</div>
							))}
						</div>
					) : (
						<span className="multi-select-placeholder">{placeholder}</span>
					)}
				</div>
				<div className="multi-select-controls">
					{selectedItems.length > 0 && (
						<button
							type="button"
							className="multi-select-clear"
							onClick={handleClearAll}
							title="Clear all selections"
							aria-label="Clear all selections"
						>
							<X size={16} />
						</button>
					)}
					<ChevronDown size={18} className={`multi-select-chevron${isOpen ? " rotated" : ""}`} />
				</div>
			</button>

			{isOpen && (
				<div className="multi-select-dropdown">
					{options.length > 0 ? (
						<div className="multi-select-options">
							{options.map((option) => (
								<div className="multi-select-option" key={option.id}>
									<input
										type="checkbox"
										id={`multi-select-${option.id}`}
										checked={selectedIds.includes(option.id)}
										onChange={() => handleToggle(option.id)}
										className="multi-select-checkbox"
										aria-label={option.name}
									/>
									<label htmlFor={`multi-select-${option.id}`} className="multi-select-option-label">
										{option.name}
									</label>
								</div>
							))}
						</div>
					) : (
						<div className="multi-select-empty">No options available</div>
					)}
				</div>
			)}
		</div>
	)
}
