// Generated by Gemini 3.6 Flash on 2026-08-29
import { ChevronDown, X } from "lucide-react"
import { useCallback, useRef, useState } from "react"
import { useClickOutside } from "../hooks/useClickOutside"

export const MultiSelect = ({ options, selectedIds, onChange, placeholder = "Select items...", ...attrs }) => {
	const [isOpen, setIsOpen] = useState(false)
	const containerRef = useRef(null)

	const selectedItems = options.filter((opt) => selectedIds.includes(opt.id))

	const handleToggle = (id) => {
		const newIds = selectedIds.includes(id) ? selectedIds.filter((selectedId) => selectedId !== id) : [...selectedIds, id]
		onChange(newIds)
	}

	const handleRemove = (id, e) => {
		e.stopPropagation()
		onChange(selectedIds.filter((selectedId) => selectedId !== id))
	}

	const handleClearAll = (e) => {
		e.stopPropagation()
		onChange([])
	}

	const handleClose = useCallback(() => setIsOpen(false), [])

	useClickOutside(containerRef, handleClose, isOpen)

	return (
		<div className="multi-select-container" ref={containerRef} {...attrs}>
			<div
				className={`multi-select-trigger${isOpen ? " open" : ""}`}
				onClick={() => setIsOpen(!isOpen)}
				onKeyDown={(event) => {
					if (event.target !== event.currentTarget) {
						return
					}
					if (event.key === "Enter" || event.key === " ") {
						event.preventDefault()
						setIsOpen((open) => !open)
					} else if (event.key === "Escape") {
						setIsOpen(false)
					}
				}}
				// biome-ignore lint/a11y/useSemanticElements: trigger must be a div to avoid nesting <button> inside <button> which is invalid HTML
				role="combobox"
				tabIndex={0}
				aria-haspopup="listbox"
				aria-expanded={isOpen}
				aria-controls="multi-select-listbox"
				aria-label="Select projects"
			>
				<div className="multi-select-value">
					{selectedItems.length > 0 ? (
						<div className="multi-select-tags">
							{selectedItems.map((item) => (
								<div className="multi-select-tag" key={item.id}>
									<span>{item.name}</span>
									<button
										type="button"
										className="multi-select-tag-remove"
										onClick={(e) => handleRemove(item.id, e)}
										title={`Remove ${item.name}`}
										aria-label={`Remove ${item.name}`}
									>
										<X size={14} />
									</button>
								</div>
							))}
						</div>
					) : (
						<span className="multi-select-placeholder">{placeholder}</span>
					)}
				</div>
				<div className="multi-select-controls">
					{selectedItems.length > 0 && (
						<button
							type="button"
							className="multi-select-clear"
							onClick={handleClearAll}
							title="Clear all selections"
							aria-label="Clear all selections"
						>
							<X size={16} />
						</button>
					)}
					<ChevronDown size={18} className={`multi-select-chevron${isOpen ? " rotated" : ""}`} />
				</div>
			</div>

			{isOpen && (
				<div id="multi-select-listbox" className="multi-select-dropdown">
					{options.length > 0 ? (
						<div className="multi-select-options">
							{options.map((option) => (
								<label className="multi-select-option" key={option.id}>
									<input
										type="checkbox"
										checked={selectedIds.includes(option.id)}
										onChange={() => handleToggle(option.id)}
										className="multi-select-checkbox"
										aria-label={option.name}
									/>
									<span className="multi-select-option-label">{option.name}</span>
								</label>
							))}
						</div>
					) : (
						<div className="multi-select-empty">No options available</div>
					)}
				</div>
			)}
		</div>
	)
}
