// Generated by Gemini 3.6 Flash on 2026-09-06
import { render, screen, waitFor } from "@testing-library/react"
import userEvent from "@testing-library/user-event"
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest"
import { Router } from "wouter"
import { memoryLocation } from "wouter/memory-location"
import { ThemeProvider } from "../context/ThemeContext"
import { Navbar } from "./Navbar"

const statusResponse = (payload) => ({
	ok: true,
	status: 200,
	text: async () => JSON.stringify(payload),
})

const renderNavbar = (path) => {
	const location = memoryLocation({ path, record: true })
	render(
		<Router hook={location.hook}>
			<ThemeProvider>
				<Navbar onOpenNewTaskModal={vi.fn()} projects={[]} enabledProjectIds={[]} onToggleProject={vi.fn()} />
			</ThemeProvider>
		</Router>,
	)
	return location
}

beforeEach(() => {
	localStorage.clear()
	vi.spyOn(globalThis, "fetch").mockRejectedValue(new TypeError("Failed to fetch"))
})

afterEach(() => {
	vi.restoreAllMocks()
})

describe("Navbar", () => {
	it("takes the brand to the board", async () => {
		const user = userEvent.setup()
		const location = renderNavbar("/projects")

		await user.click(screen.getByRole("link", { name: "Task Tracker" }))

		expect(location.history.at(-1)).toBe("/")
	})

	it("does not show a direct Projects link in the nav", () => {
		renderNavbar("/")

		expect(screen.queryByRole("link", { name: "Projects" })).not.toBeInTheDocument()
		expect(screen.queryByRole("link", { name: "Board" })).not.toBeInTheDocument()
	})

	it("reveals settings, theme toggle, and sign in inside the menu dropdown", async () => {
		const user = userEvent.setup()
		renderNavbar("/")

		expect(screen.queryByRole("menu")).not.toBeInTheDocument()

		await user.click(screen.getByRole("button", { name: "Open menu" }))

		expect(screen.getByRole("menu", { name: "Site menu" })).toBeInTheDocument()
		expect(screen.getByRole("menuitem", { name: "Settings" })).toHaveAttribute("href", "/settings")
		expect(screen.getByRole("menuitem", { name: /Switch to (Light|Dark) mode/ })).toBeInTheDocument()
		expect(screen.getByRole("menuitem", { name: "Sign in" })).toHaveAttribute("href", "/register")
	})

	it("navigates to settings from the menu dropdown", async () => {
		const user = userEvent.setup()
		const location = renderNavbar("/")

		await user.click(screen.getByRole("button", { name: "Open menu" }))
		await user.click(screen.getByRole("menuitem", { name: "Settings" }))

		expect(location.history.at(-1)).toBe("/settings")
	})

	it("keeps task creation and project filtering visible when auth is not required", async () => {
		renderNavbar("/")

		expect(await screen.findByRole("button", { name: /new task/i })).toBeInTheDocument()
		expect(screen.getByRole("button", { name: /filter/i })).toBeInTheDocument()
	})

	it("hides task creation and project filtering when auth is required and logged out", async () => {
		globalThis.fetch.mockResolvedValueOnce(statusResponse({ authenticated: false, user: null, auth_required: true }))
		renderNavbar("/")

		await waitFor(() => expect(globalThis.fetch).toHaveBeenCalled())
		await waitFor(() => expect(screen.queryByRole("button", { name: /new task/i })).not.toBeInTheDocument())
		expect(screen.queryByRole("button", { name: /filter/i })).not.toBeInTheDocument()
	})

	it("keeps task creation visible when auth is required but logged in", async () => {
		localStorage.setItem("task-tracker:auth-user", JSON.stringify({ id: 1, username: "Admin", password: "secret" }))
		globalThis.fetch.mockResolvedValueOnce(statusResponse({ authenticated: true, user: { id: 1, username: "Admin" }, auth_required: true }))
		renderNavbar("/")

		expect(await screen.findByRole("button", { name: /new task/i })).toBeInTheDocument()
		expect(screen.getByRole("button", { name: /filter/i })).toBeInTheDocument()
	})
})
