// Generated by Gemini 3.6 Flash on 2026-08-19
import { CheckSquare, FolderOpen, Moon, Plus, Sun } from "lucide-react"
import { Link } from "wouter"
import { useTheme } from "../context/ThemeContext"
import { ProjectToggleDropdown } from "./ProjectToggleDropdown"

export const Navbar = ({ onOpenNewTaskModal, projects, enabledProjectIds, onToggleProject }) => {
	const { theme, toggleTheme } = useTheme()

	return (
		<header className="navbar">
			<Link href="/" className="navbar-brand" title="Go to board">
				<div className="navbar-icon">
					<CheckSquare size={20} />
				</div>
				<h1 className="navbar-title">Task Tracker</h1>
			</Link>
			<div className="navbar-actions">
				<ProjectToggleDropdown projects={projects} enabledProjectIds={enabledProjectIds} onToggle={onToggleProject} />
				<Link href="/projects" className="btn btn-secondary" title="Manage projects">
					<FolderOpen size={18} />
					<span>Projects</span>
				</Link>
				<button type="button" className="btn btn-icon" onClick={toggleTheme} title={`Switch to ${theme === "dark" ? "Light" : "Dark"} Mode`}>
					{theme === "dark" ? <Sun size={18} /> : <Moon size={18} />}
				</button>
				<button type="button" className="btn btn-primary" onClick={onOpenNewTaskModal}>
					<Plus size={18} />
					<span>New Task</span>
				</button>
			</div>
		</header>
	)
}
