// Generated by Gemini 3.6 Flash on 2026-09-06
import { render, screen } from "@testing-library/react"
import userEvent from "@testing-library/user-event"
import { describe, expect, it, vi } from "vitest"
import { Router } from "wouter"
import { memoryLocation } from "wouter/memory-location"
import { ThemeProvider } from "../context/ThemeContext"
import { Navbar } from "./Navbar"

const renderNavbar = (path) => {
	const location = memoryLocation({ path, record: true })
	render(
		<Router hook={location.hook}>
			<ThemeProvider>
				<Navbar onOpenNewTaskModal={vi.fn()} projects={[]} enabledProjectIds={[]} onToggleProject={vi.fn()} />
			</ThemeProvider>
		</Router>,
	)
	return location
}

describe("Navbar", () => {
	it("takes the brand to the board", async () => {
		const user = userEvent.setup()
		const location = renderNavbar("/projects")

		await user.click(screen.getByRole("link", { name: "Task Tracker" }))

		expect(location.history.at(-1)).toBe("/")
	})

	it("does not show a direct Projects link in the nav", () => {
		renderNavbar("/")

		expect(screen.queryByRole("link", { name: "Projects" })).not.toBeInTheDocument()
		expect(screen.queryByRole("link", { name: "Board" })).not.toBeInTheDocument()
	})

	it("reveals settings, theme toggle, and sign in inside the menu dropdown", async () => {
		const user = userEvent.setup()
		renderNavbar("/")

		expect(screen.queryByRole("menu")).not.toBeInTheDocument()

		await user.click(screen.getByRole("button", { name: "Open menu" }))

		expect(screen.getByRole("menu", { name: "Site menu" })).toBeInTheDocument()
		expect(screen.getByRole("menuitem", { name: "Settings" })).toHaveAttribute("href", "/settings")
		expect(screen.getByRole("menuitem", { name: /Switch to (Light|Dark) mode/ })).toBeInTheDocument()
		expect(screen.getByRole("menuitem", { name: "Sign in" })).toHaveAttribute("href", "/register")
	})

	it("navigates to settings from the menu dropdown", async () => {
		const user = userEvent.setup()
		const location = renderNavbar("/")

		await user.click(screen.getByRole("button", { name: "Open menu" }))
		await user.click(screen.getByRole("menuitem", { name: "Settings" }))

		expect(location.history.at(-1)).toBe("/settings")
	})
})
