// Generated by Gemini 3.6 Flash on 2026-08-19
import React from 'react';
import { useTheme } from '../context/ThemeContext';
import { Sun, Moon, Plus, CheckSquare } from 'lucide-react';

export const Navbar = ({ onOpenNewTaskModal }) => {
  const { theme, toggleTheme } = useTheme();

  return (
    <header className="navbar">
      <div className="navbar-brand">
        <div className="navbar-icon">
          <CheckSquare size={20} />
        </div>
        <h1 className="navbar-title">Task Tracker</h1>
      </div>
      <div className="navbar-actions">
        <button
          className="btn btn-icon"
          onClick={toggleTheme}
          title={`Switch to ${theme === 'dark' ? 'Light' : 'Dark'} Mode`}
        >
          {theme === 'dark' ? <Sun size={18} /> : <Moon size={18} />}
        </button>
        <button className="btn btn-primary" onClick={onOpenNewTaskModal}>
          <Plus size={18} />
          <span>New Task</span>
        </button>
      </div>
    </header>
  );
};
