// Generated by Gemini 3.6 Flash on 2026-09-06
import { render, screen } from "@testing-library/react"
import userEvent from "@testing-library/user-event"
import { describe, expect, it, vi } from "vitest"
import { Router } from "wouter"
import { memoryLocation } from "wouter/memory-location"
import { ThemeProvider } from "../context/ThemeContext"
import { Navbar } from "./Navbar"

const renderNavbar = (path) => {
	const location = memoryLocation({ path, record: true })
	render(
		<Router hook={location.hook}>
			<ThemeProvider>
				<Navbar onOpenNewTaskModal={vi.fn()} projects={[]} enabledProjectIds={[]} onToggleProject={vi.fn()} />
			</ThemeProvider>
		</Router>,
	)
	return location
}

describe("Navbar", () => {
	it("takes the brand to the board", async () => {
		const user = userEvent.setup()
		const location = renderNavbar("/projects")

		await user.click(screen.getByRole("link", { name: "Task Tracker" }))

		expect(location.history.at(-1)).toBe("/")
	})

	it("shows a Projects link from the board", () => {
		renderNavbar("/")

		expect(screen.getByRole("link", { name: "Projects" })).toHaveAttribute("href", "/projects")
	})

	it("shows a Board link from the Projects page", () => {
		renderNavbar("/projects")

		expect(screen.getByRole("link", { name: "Board" })).toHaveAttribute("href", "/")
	})
})
