// Generated by Muse Spark 1.2 on 2026-08-31
import { useOfflineQueueContext } from "../context/OfflineQueueContext"

export const OfflineBanner = () => {
	const { queue, isOnline, isSyncing, syncQueue } = useOfflineQueueContext()

	if (!isOnline) {
		return (
			// biome-ignore lint/a11y/useSemanticElements: status banner uses div for styling
			<div className="offline-banner offline-banner-offline" role="status" aria-live="polite">
				<span>
					Offline — {queue.length} pending {queue.length === 1 ? "change" : "changes"}
				</span>
			</div>
		)
	}

	if (isSyncing) {
		return (
			// biome-ignore lint/a11y/useSemanticElements: status banner uses div for styling
			<div className="offline-banner offline-banner-syncing" role="status" aria-live="polite">
				<span className="offline-banner-spinner" aria-hidden="true" />
				<span>
					Syncing {queue.length} {queue.length === 1 ? "change" : "changes"}...
				</span>
			</div>
		)
	}

	if (queue.length > 0 && isOnline) {
		return (
			// biome-ignore lint/a11y/useSemanticElements: status banner uses div for styling
			<div className="offline-banner offline-banner-pending" role="status" aria-live="polite">
				<span>
					{queue.length} pending {queue.length === 1 ? "change" : "changes"}
				</span>
				<button type="button" className="btn btn-secondary btn-pending-retry" onClick={syncQueue}>
					Retry sync
				</button>
			</div>
		)
	}

	return null
}
