// Generated by Claude Opus 4.6 on 2026-08-29
import { ChevronDown } from "lucide-react"
import { useCallback, useRef, useState } from "react"
import { useClickOutside } from "../hooks/useClickOutside"

export const ProjectToggleDropdown = ({ projects, enabledProjectIds, onToggle }) => {
	const [isOpen, setIsOpen] = useState(false)
	const dropdownRef = useRef(null)

	const handleClose = useCallback(() => setIsOpen(false), [])

	useClickOutside(dropdownRef, handleClose, isOpen)

	const activeCount = enabledProjectIds.length

	return (
		<div className="project-dropdown" ref={dropdownRef}>
			<button
				type="button"
				className="btn btn-secondary"
				onClick={() => setIsOpen((open) => !open)}
				aria-expanded={isOpen}
				aria-haspopup="listbox"
				title="Filter by project"
			>
				<span>Filter{activeCount > 0 ? ` (${activeCount})` : ""}</span>
				<ChevronDown size={14} className={`dropdown-chevron${isOpen ? " is-open" : ""}`} />
			</button>

			{isOpen && (
				<fieldset className="project-dropdown-menu">
					<legend className="sr-only">Project filters</legend>
					{projects.length === 0 && <p className="project-dropdown-empty">No projects</p>}
					{projects.map((project) => {
						const isEnabled = enabledProjectIds.includes(project.id)
						return (
							<label className="project-dropdown-item" key={project.id}>
								<input type="checkbox" checked={isEnabled} onChange={() => onToggle(project.id)} />
								<span className="project-toggle-name" title={project.name}>
									{project.name}
								</span>
							</label>
						)
					})}
				</fieldset>
			)}
		</div>
	)
}
