// Generated by GitHub Copilot on 2026-08-25
import { Plus, Trash2 } from "lucide-react"
import { useState } from "react"

export const ProjectManager = ({ projects, enabledProjectIds, loading, error, onRetry, onToggle, onCreate, onDelete }) => {
	const [projectName, setProjectName] = useState("")

	const handleSubmit = async (event) => {
		event.preventDefault()
		const name = projectName.trim()
		if (!name) return
		const created = await onCreate(name)
		if (created) setProjectName("")
	}

	return (
		<section className="project-panel" aria-labelledby="project-panel-title">
			<div className="project-panel-header">
				<div>
					<h2 id="project-panel-title" className="project-panel-title">
						Projects
					</h2>
					<p className="project-panel-hint">Toggle projects to filter the board</p>
				</div>
				<span className="project-filter-count" aria-live="polite">
					{enabledProjectIds.length} active
				</span>
			</div>

			<form className="project-create-form" onSubmit={handleSubmit}>
				<label className="sr-only" htmlFor="new-project-name">
					Project name
				</label>
				<input
					id="new-project-name"
					type="text"
					className="form-input"
					placeholder="New project name"
					value={projectName}
					onChange={(event) => setProjectName(event.target.value)}
				/>
				<button type="submit" className="btn btn-primary" disabled={!projectName.trim()}>
					<Plus size={16} />
					<span>Add project</span>
				</button>
			</form>

			{loading && <p className="project-message">Loading projects...</p>}
			{error && (
				<div className="project-message project-error" role="alert">
					<span>{error}</span>
					<button type="button" className="btn btn-secondary" onClick={onRetry}>
						Retry
					</button>
				</div>
			)}
			{!loading && !error && projects.length === 0 && <p className="project-message">No projects yet</p>}
			{!loading && !error && projects.length > 0 && (
				<ul className="project-list">
					{projects.map((project) => {
						const isEnabled = enabledProjectIds.includes(project.id)
						return (
							<li className="project-item" key={project.id}>
								<label className="project-toggle">
									<input type="checkbox" checked={isEnabled} onChange={() => onToggle(project.id)} />
									<span className="project-toggle-name" title={project.name}>
										{project.name}
									</span>
								</label>
								<button type="button" className="btn btn-danger-ghost" onClick={() => onDelete(project.id)} title={`Delete ${project.name}`}>
									<Trash2 size={15} />
									<span className="sr-only">Delete {project.name}</span>
								</button>
							</li>
						)
					})}
				</ul>
			)}
		</section>
	)
}
