// Generated by Claude Opus 4.6 on 2026-08-29
import { Trash2 } from "lucide-react"

export const ProjectList = ({ projects, enabledProjectIds = [], onDelete, onToggle, className = "project-list project-list-page" }) => {
	if (projects.length === 0) {
		return (
			<section className="projects-empty-state" aria-labelledby="projects-empty-title">
				<h3 id="projects-empty-title">No projects yet</h3>
				<p>Use the form above to create your first project.</p>
			</section>
		)
	}

	return (
		<ul className={className}>
			{projects.map((project) => (
				<li className="project-item" key={project.id}>
					{onToggle ? (
						<label className="project-toggle">
							<input type="checkbox" checked={enabledProjectIds.includes(project.id)} onChange={() => onToggle(project.id)} />
							<span className="project-toggle-name" title={project.name}>
								{project.name}
							</span>
						</label>
					) : (
						<span className="project-toggle-name" title={project.name}>
							{project.name}
						</span>
					)}
					<button type="button" className="btn btn-danger-ghost" onClick={() => onDelete(project.id)} title={`Delete ${project.name}`}>
						<Trash2 size={15} />
						<span className="sr-only">Delete {project.name}</span>
					</button>
				</li>
			))}
		</ul>
	)
}
