// Generated by GitHub Copilot on 2026-08-25
import { CreateProjectForm } from "./CreateProjectForm"
import { ProjectList } from "./ProjectList"

export const ProjectManager = ({ projects, enabledProjectIds, loading, error, onRetry, onToggle, onCreate, onDelete }) => {
	return (
		<section className="project-panel" aria-labelledby="project-panel-title">
			<div className="project-panel-header">
				<div>
					<h2 id="project-panel-title" className="project-panel-title">
						Projects
					</h2>
					<p className="project-panel-hint">Toggle projects to filter the board</p>
				</div>
				<span className="project-filter-count" aria-live="polite">
					{enabledProjectIds.length} active
				</span>
			</div>

			<CreateProjectForm onCreate={onCreate} inputId="new-project-name" />

			{loading && <p className="project-message">Loading projects...</p>}
			{error && (
				<div className="project-message project-error" role="alert">
					<span>{error}</span>
					<button type="button" className="btn btn-secondary" onClick={onRetry}>
						Retry
					</button>
				</div>
			)}
			{!loading && !error && projects.length === 0 && <p className="project-message">No projects yet</p>}
			{!loading && !error && projects.length > 0 && (
				<ProjectList projects={projects} enabledProjectIds={enabledProjectIds} onToggle={onToggle} onDelete={onDelete} className="project-list" />
			)}
		</section>
	)
}
