// Generated by Claude Opus 4.6 on 2026-09-04
import { Check, CloudOff, Loader2 } from "lucide-react"

export const SyncIndicator = ({ status, message }) => {
	if (status === "idle") return null

	const config = {
		syncing: { icon: <Loader2 size={14} className="sync-spinner" />, className: "syncing" },
		saved: { icon: <Check size={14} />, className: "saved" },
		offline: { icon: <CloudOff size={14} />, className: "offline" },
	}

	const { icon, className } = config[status] || {}
	if (!className) return null

	return (
		<output className={`sync-indicator ${className}`} aria-live="polite">
			{icon}
			<span>{message}</span>
		</output>
	)
}
