// Generated by Gemini 3.6 Flash on 2026-08-19
import { Edit2, Trash2, User } from "lucide-react"
import { useState } from "react"
import { COLUMNS } from "../utils/constants"
import { getPriorityBadgeClass } from "../utils/taskHelpers"

export const TaskCard = ({ task, onEdit, onDelete, onStatusChange, onDragStart, onDropTask }) => {
	const [isDragging, setIsDragging] = useState(false)
	const [isDragOver, setIsDragOver] = useState(false)

	const handleDragStart = (e) => {
		setIsDragging(true)
		e.dataTransfer.setData("text/plain", String(task.id))
		e.dataTransfer.effectAllowed = "move"
		if (onDragStart) {
			onDragStart(e, task.id)
		}
	}

	const handleDragEnd = () => {
		setIsDragging(false)
	}

	const handleDragOver = (e) => {
		e.preventDefault()
		e.stopPropagation()
		e.dataTransfer.dropEffect = "move"
		if (!isDragOver) setIsDragOver(true)
	}

	const handleDragLeave = (e) => {
		e.preventDefault()
		e.stopPropagation()
		setIsDragOver(false)
	}

	const handleDrop = (e) => {
		e.preventDefault()
		e.stopPropagation()
		setIsDragOver(false)
		const taskIdStr = e.dataTransfer.getData("text/plain")
		const draggedTaskId = Number.parseInt(taskIdStr, 10)
		if (draggedTaskId && draggedTaskId !== task.id && onDropTask) {
			onDropTask(draggedTaskId, task.status, task.id)
		}
	}

	return (
		<div
			className={`task-card ${isDragging ? "dragging" : ""} ${isDragOver ? "drag-over-card" : ""}`}
			draggable={true}
			onDragStart={handleDragStart}
			onDragEnd={handleDragEnd}
			onDragOver={handleDragOver}
			onDragLeave={handleDragLeave}
			onDrop={handleDrop}
		>
			<div className="task-card-header">
				<h4 className="task-title">{task.title}</h4>
				<div className="task-card-actions">
					<button
						type="button"
						className="btn btn-icon btn-ghost-sm"
						onClick={(e) => {
							e.stopPropagation()
							onEdit(task)
						}}
						title="Edit Task"
					>
						<Edit2 size={14} />
					</button>
					<button
						type="button"
						className="btn btn-danger-ghost btn-ghost-sm"
						onClick={(e) => {
							e.stopPropagation()
							onDelete(task.id)
						}}
						title="Delete Task"
					>
						<Trash2 size={14} />
					</button>
				</div>
			</div>

			{task.description && <p className="task-description">{task.description}</p>}

			{task.projects?.length > 0 && (
				<div className="project-tags" aria-label="Associated projects">
					{task.projects.map((project) => (
						<span className="project-tag" key={project.id} title={project.name}>
							{project.name}
						</span>
					))}
				</div>
			)}

			<div className="task-meta">
				<span className={`badge ${getPriorityBadgeClass(task.priority)}`}>{task.priority}</span>

				<div className="assignee-tag">
					<User size={12} />
					<span>{task.assignee_details?.username || "Admin"}</span>
				</div>

				<select
					className="status-select"
					id={`task-status-${task.id}`}
					name="status"
					value={task.status}
					onChange={(e) => onStatusChange(task.id, e.target.value)}
					onClick={(e) => e.stopPropagation()}
					onKeyDown={(e) => e.stopPropagation()}
					onKeyUp={(e) => e.stopPropagation()}
				>
					{COLUMNS.map(({ id, title }) => (
						<option key={id} value={id}>
							{title}
						</option>
					))}
				</select>
			</div>
		</div>
	)
}
