// Generated by Gemini 3.6 Flash on 2026-08-19
import { Edit2, Trash2, User } from 'lucide-react'
import { useState } from 'react'

export const TaskCard = ({ task, onEdit, onDelete, onStatusChange, onDragStart }) => {
	const [isDragging, setIsDragging] = useState(false)

	const handleDragStart = (e) => {
		setIsDragging(true)
		e.dataTransfer.setData('text/plain', String(task.id))
		e.dataTransfer.effectAllowed = 'move'
		if (onDragStart) {
			onDragStart(e, task.id)
		}
	}

	const handleDragEnd = () => {
		setIsDragging(false)
	}

	const getPriorityBadgeClass = (priority) => {
		switch (priority) {
			case 'HIGH':
				return 'badge-priority-high'
			case 'MEDIUM':
				return 'badge-priority-medium'
			default:
				return 'badge-priority-low'
		}
	}

	return (
		<div className={`task-card ${isDragging ? 'dragging' : ''}`} draggable={true} onDragStart={handleDragStart} onDragEnd={handleDragEnd}>
			<div className="task-card-header">
				<h4 className="task-title">{task.title}</h4>
				<div style={{ display: 'flex', gap: '0.25rem' }}>
					<button
						type="button"
						className="btn btn-icon"
						style={{ padding: '0.25rem', border: 'none', background: 'transparent' }}
						onClick={(e) => {
							e.stopPropagation()
							onEdit(task)
						}}
						title="Edit Task"
					>
						<Edit2 size={14} />
					</button>
					<button
						type="button"
						className="btn btn-danger-ghost"
						style={{ padding: '0.25rem' }}
						onClick={(e) => {
							e.stopPropagation()
							onDelete(task.id)
						}}
						title="Delete Task"
					>
						<Trash2 size={14} />
					</button>
				</div>
			</div>

			{task.description && <p className="task-description">{task.description}</p>}

			<div className="task-meta">
				<span className={`badge ${getPriorityBadgeClass(task.priority)}`}>{task.priority}</span>

				<div className="assignee-tag">
					<User size={12} />
					<span>{task.assignee || 'Admin'}</span>
				</div>

				<select
					className="status-select"
					value={task.status}
					onChange={(e) => onStatusChange(task.id, e.target.value)}
					onClick={(e) => e.stopPropagation()}
					onKeyDown={(e) => e.stopPropagation()}
					onKeyUp={(e) => e.stopPropagation()}
				>
					<option value="TODO">To Do</option>
					<option value="IN_PROGRESS">In Progress</option>
					<option value="REVIEW">Review</option>
					<option value="DONE">Done</option>
				</select>
			</div>
		</div>
	)
}
