// Generated by Gemini 3.6 Flash on 2026-08-19
import { X } from "lucide-react"
import { useEffect, useState } from "react"
import { projectApi } from "../services/api"

export const TaskModal = ({ isOpen, onClose, onSave, taskToEdit }) => {
	const [formData, setFormData] = useState({
		title: "",
		description: "",
		priority: "MEDIUM",
		status: "TODO",
		assignee: "Admin",
		project_ids: [],
	})
	const [projects, setProjects] = useState([])
	const [projectsError, setProjectsError] = useState("")

	useEffect(() => {
		if (!isOpen) return
		setProjectsError("")
		projectApi
			.getProjects()
			.then(setProjects)
			.catch(() => setProjectsError("Projects could not be loaded."))
	}, [isOpen])

	useEffect(() => {
		if (taskToEdit) {
			setFormData({
				title: taskToEdit.title || "",
				description: taskToEdit.description || "",
				priority: taskToEdit.priority || "MEDIUM",
				status: taskToEdit.status || "TODO",
				assignee: taskToEdit.assignee || "Admin",
				project_ids: taskToEdit.project_ids || taskToEdit.projects?.map((project) => project.id) || [],
			})
		} else {
			setFormData({
				title: "",
				description: "",
				priority: "MEDIUM",
				status: "TODO",
				assignee: "Admin",
				project_ids: [],
			})
		}
	}, [taskToEdit])

	if (!isOpen) return null

	const handleSubmit = (e) => {
		e.preventDefault()
		if (!formData.title.trim()) return
		onSave(formData)
		onClose()
	}

	const toggleProject = (projectId) => {
		const projectIds = formData.project_ids.includes(projectId)
			? formData.project_ids.filter((id) => id !== projectId)
			: [...formData.project_ids, projectId]
		setFormData({ ...formData, project_ids: projectIds })
	}

	return (
		<div className="modal-overlay" onClick={onClose} onKeyDown={(e) => e.key === "Escape" && onClose()}>
			<div className="modal-container" onClick={(e) => e.stopPropagation()} onKeyDown={(e) => e.stopPropagation()}>
				<div className="modal-header">
					<h3 className="modal-title">{taskToEdit ? "Edit Task" : "Create New Task"}</h3>
					<button type="button" className="btn btn-icon" onClick={onClose} title="Close">
						<X size={18} />
					</button>
				</div>

				<form onSubmit={handleSubmit}>
					<div className="modal-body">
						<div className="form-group">
							<legend className="form-label">Projects</legend>
							<fieldset id="task-projects" className="project-select" aria-label="Select projects for this task">
								{projects.length > 0 ? (
									<div className="task-project-options">
										{projects.map((project) => {
											const isSelected = formData.project_ids.includes(project.id)
											return (
												<label className={`task-project-option${isSelected ? " selected" : ""}`} key={project.id}>
													<input type="checkbox" checked={isSelected} onChange={() => toggleProject(project.id)} />
													<span>{project.name}</span>
												</label>
											)
										})}
									</div>
								) : (
									<span className="form-help">No projects available</span>
								)}
							</fieldset>
							{projectsError ? (
								<span className="form-help form-error">{projectsError}</span>
							) : (
								<span className="form-help">Select zero or more projects</span>
							)}
						</div>

						<div className="form-group">
							<label className="form-label" htmlFor="task-title">
								Task Title *
							</label>
							<input
								id="task-title"
								type="text"
								className="form-input"
								placeholder="e.g. Build REST API endpoints"
								value={formData.title}
								onChange={(e) => setFormData({ ...formData, title: e.target.value })}
								required
							/>
						</div>

						<div className="form-group">
							<label className="form-label" htmlFor="task-description">
								Description
							</label>
							<textarea
								id="task-description"
								className="form-textarea"
								placeholder="Provide task details or acceptance criteria..."
								value={formData.description}
								onChange={(e) => setFormData({ ...formData, description: e.target.value })}
							/>
						</div>

						<div className="form-row">
							<div className="form-group">
								<label className="form-label" htmlFor="task-status">
									Status
								</label>
								<select
									id="task-status"
									className="form-select"
									value={formData.status}
									onChange={(e) => setFormData({ ...formData, status: e.target.value })}
								>
									<option value="TODO">To Do</option>
									<option value="IN_PROGRESS">In Progress</option>
									<option value="REVIEW">Review</option>
									<option value="DONE">Done</option>
								</select>
							</div>

							<div className="form-group">
								<label className="form-label" htmlFor="task-priority">
									Priority
								</label>
								<select
									id="task-priority"
									className="form-select"
									value={formData.priority}
									onChange={(e) => setFormData({ ...formData, priority: e.target.value })}
								>
									<option value="LOW">Low</option>
									<option value="MEDIUM">Medium</option>
									<option value="HIGH">High</option>
								</select>
							</div>
						</div>

						<div className="form-group">
							<label className="form-label" htmlFor="task-assignee">
								Assignee
							</label>
							<input
								id="task-assignee"
								type="text"
								className="form-input"
								placeholder="Admin"
								value={formData.assignee}
								onChange={(e) => setFormData({ ...formData, assignee: e.target.value })}
							/>
						</div>
					</div>

					<div className="modal-footer">
						<button type="button" className="btn btn-secondary" onClick={onClose}>
							Cancel
						</button>
						<button type="submit" className="btn btn-primary">
							{taskToEdit ? "Save Changes" : "Create Task"}
						</button>
					</div>
				</form>
			</div>
		</div>
	)
}
